.TH "libexec/ Directory Reference" 3 "4 Nov 2010" "Version 0.3.0" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libexec/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBccndc.c\fP"
.br
.PP

.RI "\fIBring up a link to another ccnd. \fP"
.ti -1c
.RI "file \fBudplink.c\fP"
.br
.PP

.RI "\fIA CCNx link adaptor for UDP. \fP"
.in -1c
