.TH "ccnd/ Directory Reference" 3 "4 Nov 2010" "Version 0.3.0" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccnd/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBandroid_main.c\fP"
.br
.ti -1c
.RI "file \fBandroid_msg.c\fP"
.br
.ti -1c
.RI "file \fBccnd.c\fP"
.br
.PP

.RI "\fIMain program of ccnd - the CCNx Daemon. \fP"
.ti -1c
.RI "file \fBccnd_internal_client.c\fP"
.br
.PP

.RI "\fIInternal client of ccnd, handles requests for inspecting and controlling operation of the ccnd; requests and responses themselves use ccn protocols. \fP"
.ti -1c
.RI "file \fBccnd_main.c\fP"
.br
.PP

.RI "\fIA CCNx program. \fP"
.ti -1c
.RI "file \fBccnd_msg.c\fP"
.br
.PP

.RI "\fILogging support for ccnd. \fP"
.ti -1c
.RI "file \fBccnd_private.h\fP"
.br
.PP

.RI "\fIPrivate definitions for ccnd - the CCNx daemon. \fP"
.ti -1c
.RI "file \fBccnd_stats.c\fP"
.br
.PP

.RI "\fIStatistics presentation for ccnd. \fP"
.ti -1c
.RI "file \fBccndsmoketest.c\fP"
.br
.PP

.RI "\fISimple program for smoke-test of ccnd. \fP"
.in -1c
