ccnd/android_msg.c
NAME
ccnd/android_msg.c -
SYNOPSIS
Functions
void ccnd_msg (struct ccnd_handle *h, const char *fmt,...)
Copyright (C) 2009,2010 Palo Alto Research Center, Inc.
void ccnd_debug_ccnb (struct ccnd_handle *h, int lineno, const char *msg, struct face *face, const unsigned char *ccnb, size_t ccnb_size)
Produce a ccnd debug trace entry.
void ccnd_usage (void)
Print the ccnd usage message on stderr.
Function Documentation
void ccnd_debug_ccnb (struct ccnd_handle * h, int lineno, const char * msg, struct face * face, const unsigned char * ccnb, size_t ccnb_size)
Produce a ccnd debug trace entry. Output is produced by calling ccnd_msg.
Parameters:
h the ccnd handle
lineno caller's source line number (usually __LINE__)
msg a short text tag to identify the entry
face handle of associated face; may be NULL
ccnb points to ccnb-encoded Interest or ContentObject
ccnb_size is in bytes
Definition at line 79 of file android_msg.c.
Referenced by adjust_outbound_for_existing_interests(), age_forwarding(), ccn_stuff_interest(), ccnd_answer_req(), ccnd_reg_prefix(), ccnd_req_unreg(), consume_matching_interests(), do_propagate(), face_send_queue_insert(), find_first_match_candidate(), mark_stale(), next_child_at_level(), pe_next_usec(), process_incoming_content(), process_incoming_interest(), propagate_interest(), remove_content(), send_content(), and set_content_timer().
void ccnd_msg (struct ccnd_handle * h, const char * fmt, ...)
Copyright (C) 2009,2010 Palo Alto Research Center, Inc. This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA. Logging support for ccnd, for Android platform Produce ccnd debug output to the Android log. Output is produced on stderr under the control of h->debug; prepends decimal timestamp and process identification. Caller should not supply newlines.
Parameters:
h the ccnd handle
fmt printf-like format string
Definition at line 47 of file android_msg.c.
Referenced by accept_connection(), ccnd_close_fd(), ccnd_collect_stats(), ccnd_create(), ccnd_debug_ccnb(), ccnd_getboundsocket(), ccnd_init_internal_keystore(), ccnd_listen_on_address(), ccnd_listen_on_wildcards(), ccnd_new_face_msg(), ccnd_parse_uri_list(), ccnd_req_destroyface(), ccnd_req_newface(), ccnd_run(), ccnd_send(), ccnd_setsockopt_v6only(), ccnd_start_notice(), ccnd_stats_http_set_debug(), check_comm_file(), content_sender(), create_local_listener(), do_deferred_write(), establish_min_recv_bufsize(), face_send_queue_insert(), finalize_content(), finalize_face(), get_outbound_faces(), handle_send_error(), main(), make_connection(), nameprefix_longest_match(), note_content_from(), process_incoming_content(), process_incoming_interest(), process_input(), process_input_buffer(), process_input_message(), propagate_interest(), record_connection(), replan_propagation(), setup_multicast(), shutdown_client_fd(), start_ccnd(), and update_forward_to().
void ccnd_usage (void)
Print the ccnd usage message on stderr. Does not exit.
Definition at line 122 of file android_msg.c.
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.