.TH "bug" 3 "4 Nov 2010" "Version 0.3.0" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 
 
.IP "\fBGlobal \fBccn_name_from_uri\fP \fP" 1c
XXX - need to error out on other uri schemes 
.PP
.PP
 
.IP "\fBGlobal \fBccnbx\fP \fP" 1c
This would be confused by attributes 
.PP

