lib/ccn_reg_mgmt.c
NAME
lib/ccn_reg_mgmt.c -
Support for parsing and creating ForwardingEntry elements.
SYNOPSIS
Functions
struct ccn_forwarding_entry * ccn_forwarding_entry_parse (const unsigned char *p, size_t size)
void ccn_forwarding_entry_destroy (struct ccn_forwarding_entry **pfe)
Destroy the result of ccn_forwarding_entry_parse().
int ccnb_append_forwarding_entry (struct ccn_charbuf *c, const struct ccn_forwarding_entry *fe)
Detailed Description
Support for parsing and creating ForwardingEntry elements.
Part of the CCNx C Library.
Copyright (C) 2009 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file ccn_reg_mgmt.c.
Function Documentation
void ccn_forwarding_entry_destroy (struct ccn_forwarding_entry ** pfe)
Destroy the result of ccn_forwarding_entry_parse().
Definition at line 101 of file ccn_reg_mgmt.c.
Referenced by ccn_forwarding_entry_parse(), ccnd_req_prefix_or_self_reg(), ccnd_req_unreg(), handle_prefix_reg_reply(), main(), and register_unregister_prefix().
struct ccn_forwarding_entry* ccn_forwarding_entry_parse (const unsigned char * p, size_t size) [read]
Definition at line 30 of file ccn_reg_mgmt.c.
Referenced by ccnd_req_prefix_or_self_reg(), ccnd_req_unreg(), handle_prefix_reg_reply(), main(), and register_unregister_prefix().
int ccnb_append_forwarding_entry (struct ccn_charbuf * c, const struct ccn_forwarding_entry * fe)
Definition at line 111 of file ccn_reg_mgmt.c.
Referenced by ccn_initiate_prefix_reg(), ccnd_req_prefix_or_self_reg(), ccnd_req_unreg(), main(), and register_unregister_prefix().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.