.TH "ccn_matrix_bounds" 3 "4 Nov 2010" "Version 0.3.0" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccn_matrix_bounds \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint_least64_t \fBrow_min\fP"
.br
.ti -1c
.RI "uint_least64_t \fBrow_max\fP"
.br
.ti -1c
.RI "unsigned \fBcol_min\fP"
.br
.ti -1c
.RI "unsigned \fBcol_max\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file matrix.h.
.SH "Field Documentation"
.PP 
.SS "unsigned \fBccn_matrix_bounds::col_max\fP"
.PP
Definition at line 36 of file matrix.h.
.PP
Referenced by ccn_matrix_getbounds(), and Dump().
.SS "unsigned \fBccn_matrix_bounds::col_min\fP"
.PP
Definition at line 35 of file matrix.h.
.PP
Referenced by ccn_matrix_getbounds(), and Dump().
.SS "uint_least64_t \fBccn_matrix_bounds::row_max\fP"
.PP
Definition at line 34 of file matrix.h.
.PP
Referenced by ccn_matrix_getbounds(), and Dump().
.SS "uint_least64_t \fBccn_matrix_bounds::row_min\fP"
.PP
Definition at line 33 of file matrix.h.
.PP
Referenced by ccn_matrix_getbounds(), and Dump().

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
