.TH "ccn_dict_entry" 3 "4 Nov 2010" "Version 0.3.0" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccn_dict_entry \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBindex\fP"
.br
.RI "\fImatches enum ccn_dtag above \fP"
.ti -1c
.RI "const char * \fBname\fP"
.br
.RI "\fItextual name of dtag \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 152 of file coding.h.
.SH "Field Documentation"
.PP 
.SS "int \fBccn_dict_entry::index\fP"
.PP
matches enum ccn_dtag above 
.PP
Definition at line 153 of file coding.h.
.PP
Referenced by ccn_extend_dict(), dtag_lookup(), and qsort_compare_dict_indices().
.SS "const char* \fBccn_dict_entry::name\fP"
.PP
textual name of dtag 
.PP
Definition at line 154 of file coding.h.
.PP
Referenced by ccn_destroy_dict(), ccn_extend_dict(), dtag_lookup(), qsort_compare_dict_indices(), and qsort_compare_dict_names().

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
