lib/ccn_interest.c
NAME
lib/ccn_interest.c -
Accessors and mutators for parsed Interest messages.
SYNOPSIS
Functions
intmax_t ccn_interest_lifetime (const unsigned char *msg, const struct ccn_parsed_interest *pi)
int ccn_interest_lifetime_seconds (const unsigned char *msg, const struct ccn_parsed_interest *pi)
Detailed Description
Accessors and mutators for parsed Interest messages.
Definition in file ccn_interest.c.
Function Documentation
intmax_t ccn_interest_lifetime (const unsigned char * msg, const struct ccn_parsed_interest * pi)"Returns:
the lifetime of the interest in units of 2**(-12) seconds (the same units as timestamps).
Definition at line 32 of file ccn_interest.c.
Referenced by ccn_construct_interest(), ccn_interest_lifetime_seconds(), main(), process_incoming_interest(), and propagate_interest().
int ccn_interest_lifetime_seconds (const unsigned char * msg, const struct ccn_parsed_interest * pi)"Returns:
the lifetime of the interest in units of seconds; any fractional part is truncated. Not useful for short-lived interests.
Definition at line 56 of file ccn_interest.c.
Referenced by main(), and process_incoming_interest().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.