lib/ccn_setup_sockaddr_un.c
NAME
lib/ccn_setup_sockaddr_un.c -
Part of the CCNx C Library.
SYNOPSIS
Functions
void ccn_setup_sockaddr_un (const char *portstr, struct sockaddr_un *result)
Set up a unix-domain socket address for contacting ccnd.
Detailed Description
Part of the CCNx C Library.
Copyright (C) 2009 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file ccn_setup_sockaddr_un.c.
Function Documentation
void ccn_setup_sockaddr_un (const char * portstr, struct sockaddr_un * result)
Set up a unix-domain socket address for contacting ccnd. If the environment variable CCN_LOCAL_SOCKNAME is set and not empty, it supplies the name stem; otherwise the compiled-in default is used.
If portstr is NULL or empty, the environment variable CCN_LOCAL_PORT is checked. If the portstr specifies something other than the ccnx registered port number, the socket name is modified accordingly.
Parameters:
portstr - numeric port; use NULL for default.
Definition at line 43 of file ccn_setup_sockaddr_un.c.
Referenced by ccn_connect(), ccnd_get_local_sockname(), and main().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.