.TH "ccn_scheduled_event" 3 "4 Nov 2010" "Version 0.3.0" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccn_scheduled_event \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBccn_scheduled_action\fP \fBaction\fP"
.br
.ti -1c
.RI "void * \fBevdata\fP"
.br
.ti -1c
.RI "intptr_t \fBevint\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 66 of file schedule.h.
.SH "Field Documentation"
.PP 
.SS "\fBccn_scheduled_action\fP \fBccn_scheduled_event::action\fP"
.PP
Definition at line 67 of file schedule.h.
.PP
Referenced by ccn_schedule_cancel(), ccn_schedule_destroy(), ccn_schedule_event(), and ccn_schedule_run_next().
.SS "void* \fBccn_scheduled_event::evdata\fP"
.PP
Definition at line 68 of file schedule.h.
.PP
Referenced by ccn_schedule_cancel(), ccn_schedule_event(), content_sender(), and do_propagate().
.SS "intptr_t \fBccn_scheduled_event::evint\fP"
.PP
Definition at line 69 of file schedule.h.
.PP
Referenced by ccn_schedule_cancel(), ccn_schedule_event(), ccnd_internal_client_refresh(), clean_deamon(), content_sender(), do_propagate(), and expire_content().

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
