lib/ccn_header.c
NAME
lib/ccn_header.c -
SYNOPSIS
Functions
int ccn_parse_tagged_required_uintmax (struct ccn_buf_decoder *d, enum ccn_dtag dtag, uintmax_t *result)
struct ccn_header * ccn_header_parse (const unsigned char *p, size_t size)
Parse a ccnb-encoded Header.
void ccn_header_destroy (struct ccn_header **ph)
int ccnb_append_header (struct ccn_charbuf *c, const struct ccn_header *h)
struct ccn_header * ccn_get_header (struct ccn *h, struct ccn_charbuf *name, int timeout)
Variables
const unsigned char meta [8] = {CCN_MARKER_CONTROL, '.', 'M', 'E', 'T', 'A', '.', 'M'}
Function Documentation
struct ccn_header* ccn_get_header (struct ccn * h, struct ccn_charbuf * name, int timeout) [read]
Definition at line 137 of file ccn_header.c.
void ccn_header_destroy (struct ccn_header ** ph)
Definition at line 104 of file ccn_header.c.
Referenced by ccn_header_parse(), and main().
struct ccn_header* ccn_header_parse (const unsigned char * p, size_t size) [read]
Parse a ccnb-encoded Header.
Definition at line 50 of file ccn_header.c.
Referenced by ccn_get_header(), and main().
int ccn_parse_tagged_required_uintmax (struct ccn_buf_decoder * d, enum ccn_dtag dtag, uintmax_t * result)
Definition at line 34 of file ccn_header.c.
Referenced by ccn_header_parse().
int ccnb_append_header (struct ccn_charbuf * c, const struct ccn_header * h)
Definition at line 115 of file ccn_header.c.
Referenced by main().
Variable Documentation
const unsigned char meta[8] = {CCN_MARKER_CONTROL, '.', 'M', 'E', 'T', 'A', '.', 'M'}
Definition at line 31 of file ccn_header.c.
Referenced by ccn_get_header().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.