.TH "ccn_timeval" 3 "4 Nov 2010" "Version 0.3.0" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccn_timeval \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long \fBs\fP"
.br
.ti -1c
.RI "unsigned \fBmicros\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file schedule.h.
.SH "Field Documentation"
.PP 
.SS "unsigned \fBccn_timeval::micros\fP"
.PP
Definition at line 39 of file schedule.h.
.PP
Referenced by ccnd_gettime(), mygettime(), and update_time().
.SS "long \fBccn_timeval::s\fP"
.PP
Definition at line 38 of file schedule.h.
.PP
Referenced by ccnd_gettime(), mygettime(), and update_time().

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
