lib/ccn_extend_dict.c
NAME
lib/ccn_extend_dict.c -
Routines for extending a dictionary such as that which represents default DTAG table.
SYNOPSIS
Functions
static int qsort_compare_dict_names (const void *x, const void *y)
static int qsort_compare_dict_indices (const void *x, const void *y)
void ccn_destroy_dict (struct ccn_dict **dp)
Destroy a dictionary dynamically allocated by ccn_extend_dict.
int ccn_extend_dict (const char *dict_file, struct ccn_dict *d, struct ccn_dict **rdp)
Create a dictionary by combining a file of key/value pairs with an existing dictionary.
Detailed Description
Routines for extending a dictionary such as that which represents default DTAG table.
Part of the CCNx C Library.
Copyright (C) 2010 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file ccn_extend_dict.c.
Function Documentation
void ccn_destroy_dict (struct ccn_dict ** dp)
Destroy a dictionary dynamically allocated by ccn_extend_dict. Parameters:
dp Pointer to a pointer to a ccn_dict which will be freed and set to NULL
Definition at line 59 of file ccn_extend_dict.c.
int ccn_extend_dict (const char * dict_file, struct ccn_dict * d, struct ccn_dict ** rdp)
Create a dictionary by combining a file of key/value pairs with an existing dictionary. Parameters:
dict_file the name of a file containing integer,name pairs one per line
d a pre-existing dictionary that will be copied in the result
rdp a pointer to storage into which a pointer to the result dictionary will be stored
Returns:
0 if the new dictionary was created successfully, otherwise -1.
Definition at line 84 of file ccn_extend_dict.c.
Referenced by main().
static int qsort_compare_dict_indices (const void * x, const void * y) [static]
Definition at line 42 of file ccn_extend_dict.c.
Referenced by ccn_extend_dict().
static int qsort_compare_dict_names (const void * x, const void * y) [static]
Definition at line 30 of file ccn_extend_dict.c.
Referenced by ccn_extend_dict().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.