lib/ccn_keystore.c
NAME
lib/ccn_keystore.c -
Support for keystore access.
SYNOPSIS
Functions
struct ccn_keystore * ccn_keystore_create (void)
void ccn_keystore_destroy (struct ccn_keystore **p)
int ccn_keystore_init (struct ccn_keystore *p, char *name, char *password)
struct ccn_pkey * ccn_keystore_private_key (struct ccn_keystore *p)
struct ccn_pkey * ccn_keystore_public_key (struct ccn_keystore *p)
ssize_t ccn_keystore_public_key_digest_length (struct ccn_keystore *p)
const unsigned char * ccn_keystore_public_key_digest (struct ccn_keystore *p)
struct ccn_certificate * ccn_keystore_certificate (struct ccn_keystore *p)
Detailed Description
Support for keystore access.
Part of the CCNx C Library.
Copyright (C) 2009 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file ccn_keystore.c.
Function Documentation
struct ccn_certificate* ccn_keystore_certificate (struct ccn_keystore * p) [read]
Definition at line 123 of file ccn_keystore.c.
struct ccn_keystore* ccn_keystore_create (void) [read]
Definition at line 37 of file ccn_keystore.c.
Referenced by ccn_load_private_key(), and main().
void ccn_keystore_destroy (struct ccn_keystore ** p)
Definition at line 44 of file ccn_keystore.c.
Referenced by ccn_load_private_key(), finalize_keystore(), and main().
int ccn_keystore_init (struct ccn_keystore * p, char * name, char * password)
Definition at line 59 of file ccn_keystore.c.
Referenced by ccn_load_private_key(), and main().
struct ccn_pkey* ccn_keystore_private_key (struct ccn_keystore * p) [read]
Definition at line 91 of file ccn_keystore.c.
Referenced by ccn_sign_content(), create_face(), main(), and register_unregister_prefix().
struct ccn_pkey* ccn_keystore_public_key (struct ccn_keystore * p) [read]
Definition at line 100 of file ccn_keystore.c.
Referenced by ccn_get_public_key(), ccn_sign_content(), main(), and signed_info_create().
const unsigned char* ccn_keystore_public_key_digest (struct ccn_keystore * p)
Definition at line 115 of file ccn_keystore.c.
Referenced by ccn_get_public_key(), ccn_load_private_key(), ccn_sign_content(), main(), and signed_info_create().
ssize_t ccn_keystore_public_key_digest_length (struct ccn_keystore * p)
Definition at line 109 of file ccn_keystore.c.
Referenced by ccn_get_public_key(), ccn_load_private_key(), ccn_sign_content(), main(), and signed_info_create().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.