cmd/ccn_splitccnb.c
NAME
cmd/ccn_splitccnb.c -
Utility to break up a file filled with ccnb-encoded data items into one data item per file.
SYNOPSIS
Functions
static char * segment_prefix (char *path)
static int write_segment (unsigned char *data, size_t s, struct fstate *perfilestate)
static int process_test (unsigned char *data, size_t n, struct fstate *perfilestate)
static int process_fd (int fd, struct fstate *perfilestate)
static int process_file (char *path, struct fstate *perfilestate)
int main (int argc, char *argv[])
Detailed Description
Utility to break up a file filled with ccnb-encoded data items into one data item per file.
A CCNx command-line utility.
Copyright (C) 2008, 2009 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file ccn_splitccnb.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 160 of file ccn_splitccnb.c.
static int process_fd (int fd, struct fstate * perfilestate) [static]
Definition at line 119 of file ccn_splitccnb.c.
Referenced by process_file().
static int process_file (char * path, struct fstate * perfilestate) [static]
Definition at line 138 of file ccn_splitccnb.c.
Referenced by main().
static int process_test (unsigned char * data, size_t n, struct fstate * perfilestate) [static]
Definition at line 79 of file ccn_splitccnb.c.
Referenced by process_fd().
static char* segment_prefix (char * path) [static]
Definition at line 41 of file ccn_splitccnb.c.
Referenced by process_file().
static int write_segment (unsigned char * data, size_t s, struct fstate * perfilestate) [static]
Definition at line 55 of file ccn_splitccnb.c.
Referenced by process_test().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.