include/ccn/ccn_private.h
NAME
include/ccn/ccn_private.h -
Additional operations that are irrevalent for most clients.
SYNOPSIS
Functions
void ccn_dispatch_message (struct ccn *h, unsigned char *msg, size_t size)
Dispatch a message through the registered upcalls.
int ccn_process_scheduled_operations (struct ccn *h)
Process any scheduled operations that are due.
struct ccn_charbuf * ccn_grab_buffered_output (struct ccn *h)
void ccn_setup_sockaddr_un (const char *, struct sockaddr_un *)
Set up a unix-domain socket address for contacting ccnd.
Detailed Description
Additional operations that are irrevalent for most clients.
Part of the CCNx C Library.
Copyright (C) 2009 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file ccn_private.h.
Function Documentation
void ccn_dispatch_message (struct ccn * h, unsigned char * msg, size_t size)
Dispatch a message through the registered upcalls. This is not used by normal ccn clients, but is made available for use when ccnd needs to communicate with its internal client.
Parameters:
h is the ccn handle.
msg is the ccnb-encoded Interest or ContentObject.
size is its size in bytes.
Definition at line 1130 of file ccn_client.c.
Referenced by ccn_process_input(), and ccnd_send().
struct ccn_charbuf* ccn_grab_buffered_output (struct ccn * h) [read]
Definition at line 716 of file ccn_client.c.
Referenced by process_internal_client_buffer().
int ccn_process_scheduled_operations (struct ccn * h)
Process any scheduled operations that are due. This is not used by normal ccn clients, but is made available for use by ccnd to run its internal client.
Parameters:
h is the ccn handle.
Returns:
the number of microseconds until the next thing needs to happen.
Definition at line 1414 of file ccn_client.c.
Referenced by ccn_run(), and ccnd_internal_client_refresh().
void ccn_setup_sockaddr_un (const char * portstr, struct sockaddr_un * result)
Set up a unix-domain socket address for contacting ccnd. If the environment variable CCN_LOCAL_SOCKNAME is set and not empty, it supplies the name stem; otherwise the compiled-in default is used.
If portstr is NULL or empty, the environment variable CCN_LOCAL_PORT is checked. If the portstr specifies something other than the ccnx registered port number, the socket name is modified accordingly.
Parameters:
portstr - numeric port; use NULL for default.
Definition at line 43 of file ccn_setup_sockaddr_un.c.
Referenced by ccn_connect(), ccnd_get_local_sockname(), and main().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.