.TH "ccn_parsed_ContentObject" 3 "4 Nov 2010" "Version 0.3.0" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccn_parsed_ContentObject \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmagic\fP"
.br
.ti -1c
.RI "enum \fBccn_content_type\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBname_ncomps\fP"
.br
.ti -1c
.RI "unsigned short \fBoffset\fP [CCN_PCO_E+1]"
.br
.ti -1c
.RI "unsigned char \fBdigest\fP [32]"
.br
.ti -1c
.RI "int \fBdigest_bytes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 586 of file ccn.h.
.SH "Field Documentation"
.PP 
.SS "unsigned char \fBccn_parsed_ContentObject::digest\fP[32]"
.PP
Definition at line 591 of file ccn.h.
.PP
Referenced by ccn_content_matches_interest(), ccn_digest_ContentObject(), incoming_content(), and process_incoming_content().
.SS "int \fBccn_parsed_ContentObject::digest_bytes\fP"
.PP
Definition at line 592 of file ccn.h.
.PP
Referenced by ccn_content_matches_interest(), ccn_digest_ContentObject(), ccn_parse_ContentObject(), incoming_content(), and process_incoming_content().
.SS "int \fBccn_parsed_ContentObject::magic\fP"
.PP
Definition at line 587 of file ccn.h.
.PP
Referenced by ccn_digest_Content(), ccn_digest_ContentObject(), ccn_parse_ContentObject(), and process_incoming_content().
.SS "int \fBccn_parsed_ContentObject::name_ncomps\fP"
.PP
Definition at line 589 of file ccn.h.
.PP
Referenced by ccn_content_matches_interest(), and ccn_parse_ContentObject().
.SS "unsigned short \fBccn_parsed_ContentObject::offset\fP[CCN_PCO_E+1]"
.PP
Definition at line 590 of file ccn.h.
.PP
Referenced by ccn_content_get_value(), ccn_content_matches_interest(), ccn_digest_Content(), ccn_digest_ContentObject(), ccn_initiate_key_fetch(), ccn_locate_key(), ccn_merkle_root_hash(), ccn_parse_ContentObject(), ccn_parse_Signature(), ccn_parse_SignedInfo(), ccn_pubid_matches(), ccn_verify_content(), ccn_verify_signature(), get_ccndid(), handle_key(), handle_ping_response(), handle_prefix_reg_reply(), handle_simple_incoming_content(), imcoming_bulkdata(), incoming_content(), interest_handler(), is_final(), main(), process_incoming_content(), and set_content_timer().
.SS "enum \fBccn_content_type\fP \fBccn_parsed_ContentObject::type\fP"
.PP
Definition at line 588 of file ccn.h.
.PP
Referenced by ccn_get_content_type(), ccn_parse_SignedInfo(), ccn_resolve_version(), incoming_content(), and process_incoming_content().

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
