.TH "ccn_gettime" 3 "4 Nov 2010" "Version 0.3.0" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccn_gettime \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBdescr\fP [8]"
.br
.ti -1c
.RI "\fBccn_gettime_action\fP \fBgettime\fP"
.br
.ti -1c
.RI "unsigned \fBmicros_per_base\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file schedule.h.
.SH "Field Documentation"
.PP 
.SS "void* \fBccn_gettime::data\fP"
.PP
Definition at line 48 of file schedule.h.
.PP
Referenced by ccnd_create().
.SS "char \fBccn_gettime::descr\fP[8]"
.PP
Definition at line 45 of file schedule.h.
.PP
Referenced by ccnd_create().
.SS "\fBccn_gettime_action\fP \fBccn_gettime::gettime\fP"
.PP
Definition at line 46 of file schedule.h.
.PP
Referenced by ccnd_create().
.SS "unsigned \fBccn_gettime::micros_per_base\fP"
.PP
Definition at line 47 of file schedule.h.
.PP
Referenced by ccnd_create().

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
