cmd/ccncatchunks2.c
NAME
cmd/ccncatchunks2.c -
Reads stuff written by ccnsendchunks, writes to stdout.
SYNOPSIS
Defines
#define PIPELIMIT (1U << 7)
#define GOT_HERE() ((void)(__LINE__))
Functions
static int fill_holes (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
static void usage (const char *progname)
static void mygettime (const struct ccn_gettime *self, struct ccn_timeval *result)
static void update_rtt (struct mydata *md, int incoming, unsigned slot)
static int reporter (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
void print_summary (struct mydata *md)
struct ccn_charbuf * make_template (struct mydata *md)
static struct ccn_charbuf * sequenced_name (struct mydata *md, uintmax_t seq)
static void ask_more (struct mydata *md, uintmax_t seq)
static enum ccn_upcall_res hole_filled (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
static int is_final (struct ccn_upcall_info *info)
enum ccn_upcall_res incoming_content (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
int main (int argc, char **argv)
Variables
static FILE * logstream = NULL
static struct ccn_gettime myticker
Detailed Description
Reads stuff written by ccnsendchunks, writes to stdout.
A CCNx command-line utility.
Copyright (C) 2008-2010 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file ccncatchunks2.c.
Define Documentation
#define GOT_HERE() ((void)(__LINE__))
Definition at line 35 of file ccncatchunks2.c.
#define PIPELIMIT (1U << 7)
Definition at line 33 of file ccncatchunks2.c.
Referenced by ask_more(), incoming_content(), and main().
Function Documentation
static void ask_more (struct mydata * md, uintmax_t seq) [static]
Definition at line 271 of file ccncatchunks2.c.
Referenced by incoming_content(), and main().
static int fill_holes (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Definition at line 311 of file ccncatchunks2.c.
Referenced by update_rtt().
static enum ccn_upcall_res hole_filled (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info) [static]
Definition at line 301 of file ccncatchunks2.c.
Referenced by fill_holes().
enum ccn_upcall_res incoming_content (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info)
Definition at line 391 of file ccncatchunks2.c.
static int is_final (struct ccn_upcall_info * info) [static]
Definition at line 356 of file ccncatchunks2.c.
Referenced by incoming_content().
int main (int argc, char ** argv)
Definition at line 513 of file ccncatchunks2.c.
struct ccn_charbuf* make_template (struct mydata * md) [read]
Definition at line 232 of file ccncatchunks2.c.
static void mygettime (const struct ccn_gettime * self, struct ccn_timeval * result) [static]
Definition at line 101 of file ccncatchunks2.c.
void print_summary (struct mydata * md)
Definition at line 199 of file ccncatchunks2.c.
Referenced by incoming_content(), and main().
static int reporter (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Definition at line 167 of file ccncatchunks2.c.
Referenced by fill_holes(), and main().
static struct ccn_charbuf* sequenced_name (struct mydata * md, uintmax_t seq) [static, read]
Definition at line 252 of file ccncatchunks2.c.
Referenced by ask_more(), and fill_holes().
static void update_rtt (struct mydata * md, int incoming, unsigned slot) [static]
Definition at line 117 of file ccncatchunks2.c.
Referenced by ask_more(), and incoming_content().
static void usage (const char * progname) [static]
Definition at line 87 of file ccncatchunks2.c.
Variable Documentation
FILE* logstream = NULL [static]
Definition at line 84 of file ccncatchunks2.c.
Referenced by main(), and update_rtt().
struct ccn_gettime myticker [static]"Initial value:
 {
    'timer',
    &mygettime,
    1000000,
    NULL
}
Definition at line 109 of file ccncatchunks2.c.
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.