ccnd/ccnd_stats.c
NAME
ccnd/ccnd_stats.c -
Statistics presentation for ccnd.
SYNOPSIS
Defines
#define CRLF '\r\n'
#define NL '\n'
Functions
static int ccnd_collect_stats (struct ccnd_handle *h, struct ccnd_stats *ans)
static struct ccn_charbuf * collect_stats_html (struct ccnd_handle *h)
static void send_http_response (struct ccnd_handle *h, struct face *face, const char *mime_type, struct ccn_charbuf *response)
static struct ccn_charbuf * collect_stats_xml (struct ccnd_handle *h)
static void ccnd_stats_http_set_debug (struct ccnd_handle *h, struct face *face, int level)
int ccnd_stats_handle_http_connection (struct ccnd_handle *h, struct face *face)
static void collect_faces_html (struct ccnd_handle *h, struct ccn_charbuf *b)
static void collect_forwarding_html (struct ccnd_handle *h, struct ccn_charbuf *b)
static unsigned ccnd_colorhash (struct ccnd_handle *h)
static void collect_faces_xml (struct ccnd_handle *h, struct ccn_charbuf *b)
static void collect_forwarding_xml (struct ccnd_handle *h, struct ccn_charbuf *b)
Variables
static const char * resp404
static const char * resp405
Detailed Description
Statistics presentation for ccnd.
Part of ccnd - the CCNx Daemon.
Copyright (C) 2008-2010 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file ccnd_stats.c.
Define Documentation
#define CRLF '\r\n'
Definition at line 46 of file ccnd_stats.c.
Referenced by ccnd_stats_http_set_debug(), main(), and send_http_response().
#define NL '\n'
Definition at line 47 of file ccnd_stats.c.
Referenced by collect_faces_html(), collect_faces_xml(), collect_forwarding_html(), collect_stats_html(), and collect_stats_xml().
Function Documentation
static int ccnd_collect_stats (struct ccnd_handle * h, struct ccnd_stats * ans) [static]
Definition at line 168 of file ccnd_stats.c.
Referenced by collect_stats_html(), and collect_stats_xml().
static unsigned ccnd_colorhash (struct ccnd_handle * h) [static]
Definition at line 304 of file ccnd_stats.c.
Referenced by collect_stats_html().
int ccnd_stats_handle_http_connection (struct ccnd_handle * h, struct face * face)
Definition at line 86 of file ccnd_stats.c.
Referenced by process_input().
static void ccnd_stats_http_set_debug (struct ccnd_handle * h, struct face * face, int level) [static]
Definition at line 73 of file ccnd_stats.c.
Referenced by ccnd_stats_handle_http_connection().
static void collect_faces_html (struct ccnd_handle * h, struct ccn_charbuf * b) [static]
Definition at line 210 of file ccnd_stats.c.
Referenced by collect_stats_html().
static void collect_faces_xml (struct ccnd_handle * h, struct ccn_charbuf * b) [static]
Definition at line 380 of file ccnd_stats.c.
Referenced by collect_stats_xml().
static void collect_forwarding_html (struct ccnd_handle * h, struct ccn_charbuf * b) [static]
Definition at line 261 of file ccnd_stats.c.
Referenced by collect_stats_html().
static void collect_forwarding_xml (struct ccnd_handle * h, struct ccn_charbuf * b) [static]
Definition at line 417 of file ccnd_stats.c.
Referenced by collect_stats_xml().
static struct ccn_charbuf * collect_stats_html (struct ccnd_handle * h) [static, read]
Definition at line 314 of file ccnd_stats.c.
Referenced by ccnd_stats_handle_http_connection().
static struct ccn_charbuf * collect_stats_xml (struct ccnd_handle * h) [static, read]
Definition at line 460 of file ccnd_stats.c.
Referenced by ccnd_stats_handle_http_connection().
static void send_http_response (struct ccnd_handle * h, struct face * face, const char * mime_type, struct ccn_charbuf * response) [static]
Definition at line 145 of file ccnd_stats.c.
Referenced by ccnd_stats_handle_http_connection(), and ccnd_stats_http_set_debug().
Variable Documentation
const char* resp404 [static]"Initial value:
    'HTTP/1.1 404 Not Found' CRLF
    'Connection: close' CRLF CRLF
Definition at line 64 of file ccnd_stats.c.
Referenced by ccnd_stats_handle_http_connection().
const char* resp405 [static]"Initial value:
    'HTTP/1.1 405 Method Not Allowed' CRLF
    'Connection: close' CRLF CRLF
Definition at line 68 of file ccnd_stats.c.
Referenced by ccnd_stats_handle_http_connection().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.