.TH "cmd/ccndumpnames.c" 3 "4 Nov 2010" "Version 0.3.0" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmd/ccndumpnames.c \- 
.PP
Dumps names of everything quickly retrievable to stdout.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBccn_dump_names\fP (struct ccn *h, struct \fBccn_charbuf\fP *name_prefix, int local_scope, int allow_stale)"
.br
.RI "\fIThis is a temporary interface, don't even bother to put it in a header file. \fP"
.ti -1c
.RI "static void \fBusage\fP (const char *progname)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Dumps names of everything quickly retrievable to stdout. 

A CCNx command-line utility.
.PP
Copyright (C) 2008, 2009 Palo Alto Research Center, Inc.
.PP
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA. 
.PP
Definition in file \fBccndumpnames.c\fP.
.SH "Function Documentation"
.PP 
.SS "void ccn_dump_names (struct ccn * h, struct \fBccn_charbuf\fP * name_prefix, int local_scope, int allow_stale)"
.PP
This is a temporary interface, don't even bother to put it in a header file. 
.PP
Definition at line 373 of file ccn_traverse.c.
.PP
Referenced by main().
.SS "int main (int argc, char ** argv)"
.PP
Definition at line 49 of file ccndumpnames.c.
.SS "static void usage (const char * progname)\fC [static]\fP"
.PP
Definition at line 38 of file ccndumpnames.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
