.TH "ccnd/ccnd_internal_client.c" 3 "4 Nov 2010" "Version 0.3.0" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccnd/ccnd_internal_client.c \- 
.PP
Internal client of ccnd, handles requests for inspecting and controlling operation of the ccnd; requests and responses themselves use ccn protocols.  

.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBGOT_HERE\fP"
.br
.ti -1c
.RI "#define \fBCCND_NOTICE_NAME\fP   'notice.txt'"
.br
.ti -1c
.RI "#define \fBCCND_TEST_100137\fP   0"
.br
.ti -1c
.RI "#define \fBMORECOMPS_MASK\fP   0x007F"
.br
.RI "\fILocal interpretation of selfp->intdata. \fP"
.ti -1c
.RI "#define \fBMUST_VERIFY\fP   0x0080"
.br
.ti -1c
.RI "#define \fBMUST_VERIFY1\fP   (MUST_VERIFY + 1)"
.br
.ti -1c
.RI "#define \fBOPER_MASK\fP   0xFF00"
.br
.ti -1c
.RI "#define \fBOP_PING\fP   0x0000"
.br
.ti -1c
.RI "#define \fBOP_NEWFACE\fP   0x0200"
.br
.ti -1c
.RI "#define \fBOP_DESTROYFACE\fP   0x0300"
.br
.ti -1c
.RI "#define \fBOP_PREFIXREG\fP   0x0400"
.br
.ti -1c
.RI "#define \fBOP_SELFREG\fP   0x0500"
.br
.ti -1c
.RI "#define \fBOP_UNREG\fP   0x0600"
.br
.ti -1c
.RI "#define \fBOP_NOTICE\fP   0x0700"
.br
.ti -1c
.RI "#define \fBOP_SERVICE\fP   0x0800"
.br
.ti -1c
.RI "#define \fBCCND_ID_TEMPL\fP   'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'"
.br
.ti -1c
.RI "#define \fBCCN_PATH_VAR_TMP\fP   '/var/tmp'"
.br
.ti -1c
.RI "#define \fBCCND_KEYSTORE_PASS\fP   '\\010\\043\\103\\375\\327\\237\\152\\351\\155'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBccnd_start_notice\fP (struct \fBccnd_handle\fP *ccnd)"
.br
.ti -1c
.RI "static void \fBccnd_internal_client_reschedule\fP (struct \fBccnd_handle\fP *ccnd)"
.br
.ti -1c
.RI "static void \fBccnd_init_service_ccnb\fP (struct \fBccnd_handle\fP *ccnd)"
.br
.ti -1c
.RI "static enum \fBccn_upcall_res\fP \fBccnd_answer_req\fP (struct \fBccn_closure\fP *selfp, enum \fBccn_upcall_kind\fP kind, struct \fBccn_upcall_info\fP *info)"
.br
.RI "\fICommon interest handler for ccnd_internal_client. \fP"
.ti -1c
.RI "static int \fBccnd_internal_client_refresh\fP (struct ccn_schedule *sched, void *clienth, struct \fBccn_scheduled_event\fP *ev, int flags)"
.br
.ti -1c
.RI "static void \fBccnd_uri_listen\fP (struct \fBccnd_handle\fP *ccnd, const char *uri, \fBccn_handler\fP p, intptr_t intdata)"
.br
.ti -1c
.RI "static void \fBccnd_reg_ccnx_ccndid\fP (struct \fBccnd_handle\fP *ccnd)"
.br
.RI "\fIMake a forwarding table entry for ccnx:/ccnx/CCNDID. \fP"
.ti -1c
.RI "int \fBccnd_init_internal_keystore\fP (struct \fBccnd_handle\fP *ccnd)"
.br
.ti -1c
.RI "static int \fBpost_face_notice\fP (struct \fBccnd_handle\fP *ccnd, unsigned faceid)"
.br
.ti -1c
.RI "static int \fBccnd_notice_push\fP (struct ccn_schedule *sched, void *clienth, struct \fBccn_scheduled_event\fP *ev, int flags)"
.br
.ti -1c
.RI "void \fBccnd_face_status_change\fP (struct \fBccnd_handle\fP *ccnd, unsigned faceid)"
.br
.RI "\fICalled by ccnd when a \fBface\fP undergoes a substantive status change that should be reported to interested parties. \fP"
.ti -1c
.RI "int \fBccnd_internal_client_start\fP (struct \fBccnd_handle\fP *ccnd)"
.br
.ti -1c
.RI "void \fBccnd_internal_client_stop\fP (struct \fBccnd_handle\fP *ccnd)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal client of ccnd, handles requests for inspecting and controlling operation of the ccnd; requests and responses themselves use ccn protocols. 

Part of ccnd - the CCNx Daemon.
.PP
Copyright (C) 2009-2010 Palo Alto Research Center, Inc.
.PP
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA. 
.PP
Definition in file \fBccnd_internal_client.c\fP.
.SH "Define Documentation"
.PP 
.SS "#define CCN_PATH_VAR_TMP   '/var/tmp'"
.PP
Definition at line 368 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_init_internal_keystore().
.SS "#define CCND_ID_TEMPL   'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'"
.PP
Definition at line 292 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_internal_client_start(), and ccnd_uri_listen().
.SS "#define CCND_KEYSTORE_PASS   '\\010\\043\\103\\375\\327\\237\\152\\351\\155'"
.PP
Definition at line 377 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_init_internal_keystore().
.SS "#define CCND_NOTICE_NAME   'notice.txt'"
.PP
Definition at line 46 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_internal_client_start(), and ccnd_start_notice().
.SS "#define CCND_TEST_100137   0"
.PP
Definition at line 49 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_answer_req().
.SS "#define GOT_HERE"
.PP
Definition at line 44 of file ccnd_internal_client.c.
.SS "#define MORECOMPS_MASK   0x007F"
.PP
Local interpretation of selfp->intdata. 
.PP
Definition at line 107 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_answer_req().
.SS "#define MUST_VERIFY   0x0080"
.PP
Definition at line 108 of file ccnd_internal_client.c.
.SS "#define MUST_VERIFY1   (MUST_VERIFY + 1)"
.PP
Definition at line 109 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_internal_client_start().
.SS "#define OP_DESTROYFACE   0x0300"
.PP
Definition at line 113 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_answer_req(), and ccnd_internal_client_start().
.SS "#define OP_NEWFACE   0x0200"
.PP
Definition at line 112 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_answer_req(), and ccnd_internal_client_start().
.SS "#define OP_NOTICE   0x0700"
.PP
Definition at line 117 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_answer_req(), and ccnd_internal_client_start().
.SS "#define OP_PING   0x0000"
.PP
Definition at line 111 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_answer_req(), and ccnd_internal_client_start().
.SS "#define OP_PREFIXREG   0x0400"
.PP
Definition at line 114 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_answer_req(), and ccnd_internal_client_start().
.SS "#define OP_SELFREG   0x0500"
.PP
Definition at line 115 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_answer_req(), and ccnd_internal_client_start().
.SS "#define OP_SERVICE   0x0800"
.PP
Definition at line 118 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_answer_req(), and ccnd_internal_client_start().
.SS "#define OP_UNREG   0x0600"
.PP
Definition at line 116 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_answer_req(), ccnd_internal_client_start(), and process_prefix_face_list_item().
.SS "#define OPER_MASK   0xFF00"
.PP
Definition at line 110 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_answer_req().
.SH "Function Documentation"
.PP 
.SS "static enum \fBccn_upcall_res\fP ccnd_answer_req (struct \fBccn_closure\fP * selfp, enum \fBccn_upcall_kind\fP kind, struct \fBccn_upcall_info\fP * info)\fC [static]\fP"
.PP
Common interest handler for ccnd_internal_client. 
.PP
Definition at line 123 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_internal_client_start().
.SS "void ccnd_face_status_change (struct \fBccnd_handle\fP * ccnd, unsigned faceid)"
.PP
Called by ccnd when a \fBface\fP undergoes a substantive status change that should be reported to interested parties. In the destroy case, this is called frome the hash table finalizer, so it shouldn't do much directly. Inspecting the \fBface\fP is OK, though. 
.PP
Definition at line 522 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_start_notice(), finalize_face(), and register_new_face().
.SS "int ccnd_init_internal_keystore (struct \fBccnd_handle\fP * ccnd)"
.PP
Definition at line 381 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_create(), and ccnd_internal_client_start().
.SS "static void ccnd_init_service_ccnb (struct \fBccnd_handle\fP * ccnd)\fC [static]\fP"
.PP
Definition at line 56 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_answer_req().
.SS "static int ccnd_internal_client_refresh (struct ccn_schedule * sched, void * clienth, struct \fBccn_scheduled_event\fP * ev, int flags)\fC [static]\fP"
.PP
Definition at line 273 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_internal_client_reschedule(), and ccnd_internal_client_start().
.SS "static void ccnd_internal_client_reschedule (struct \fBccnd_handle\fP * ccnd)\fC [static]\fP"
.PP
Definition at line 615 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_notice_push().
.SS "int ccnd_internal_client_start (struct \fBccnd_handle\fP * ccnd)"
.PP
Definition at line 570 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_create().
.SS "void ccnd_internal_client_stop (struct \fBccnd_handle\fP * ccnd)"
.PP
Definition at line 627 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_destroy().
.SS "static int ccnd_notice_push (struct ccn_schedule * sched, void * clienth, struct \fBccn_scheduled_event\fP * ev, int flags)\fC [static]\fP"
.PP
Definition at line 480 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_face_status_change().
.SS "static void ccnd_reg_ccnx_ccndid (struct \fBccnd_handle\fP * ccnd)\fC [static]\fP"
.PP
Make a forwarding table entry for ccnx:/ccnx/CCNDID. This one entry handles most of the namespace served by the ccnd internal client. 
.PP
Definition at line 346 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_internal_client_start().
.SS "static void ccnd_start_notice (struct \fBccnd_handle\fP * ccnd)\fC [static]\fP"
.PP
Definition at line 536 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_answer_req().
.SS "static void ccnd_uri_listen (struct \fBccnd_handle\fP * ccnd, const char * uri, \fBccn_handler\fP p, intptr_t intdata)\fC [static]\fP"
.PP
Definition at line 295 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_internal_client_start().
.SS "static int post_face_notice (struct \fBccnd_handle\fP * ccnd, unsigned faceid)\fC [static]\fP"
.PP
Definition at line 451 of file ccnd_internal_client.c.
.PP
Referenced by ccnd_notice_push().
.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
