ccnd/ccnd_private.h
NAME
ccnd/ccnd_private.h -
Private definitions for ccnd - the CCNx daemon.
SYNOPSIS
Data Structures
struct ccnd_handle
We pass this handle almost everywhere within ccnd.
struct content_queue
struct face
One of our active faces.
struct content_entry
The content hash table is keyed by the initial portion of the ContentObject that contains all the parts of the complete name.
struct sparse_straggler_entry
The sparse_straggler hash table, keyed by accession, holds scattered entries that would otherwise bloat the direct content_by_accession table.
struct propagating_entry
The propagating interest hash table is keyed by Nonce.
struct nameprefix_entry
The nameprefix hash table is keyed by the Component elements of the Name prefix.
struct ccn_forwarding
Keeps track of the faces that interests matching a given name prefix may be forwarded to.
Defines
#define FACESLOTBITS 18
Each face is referenced by a number, the faceid.
#define MAXFACES ((1U << FACESLOTBITS) - 1)
#define CCN_FACE_LINK (1 << 0)
face flags
#define CCN_FACE_DGRAM (1 << 1)
Datagram interface, respect packets.
#define CCN_FACE_GG (1 << 2)
Considered friendly.
#define CCN_FACE_LOCAL (1 << 3)
PF_UNIX socket.
#define CCN_FACE_INET (1 << 4)
IPv4.
#define CCN_FACE_MCAST (1 << 5)
a party line (e.g.
#define CCN_FACE_INET6 (1 << 6)
IPv6.
#define CCN_FACE_DC (1 << 7)
Direct control face.
#define CCN_FACE_NOSEND (1 << 8)
Don't send anymore.
#define CCN_FACE_UNDECIDED (1 << 9)
Might not be talking ccn.
#define CCN_FACE_PERMANENT (1 << 10)
No timeout for inactivity.
#define CCN_FACE_CONNECTING (1 << 11)
Connect in progress.
#define CCN_FACE_LOOPBACK (1 << 12)
v4 or v6 loopback address
#define CCN_FACE_CLOSING (1 << 13)
close stream when output is done
#define CCN_FACE_PASSIVE (1 << 14)
a listener or a bound dgram socket
#define CCN_FACE_NORECV (1 << 15)
use for sending only
#define CCN_FACE_REGOK (1 << 16)
Allowed to do prefix registration.
#define CCN_NOFACEID (~0U)
#define CCN_CONTENT_ENTRY_SLOWSEND 1
content_entry flags
#define CCN_CONTENT_ENTRY_STALE 2
#define CCN_CONTENT_ENTRY_PRECIOUS 4
#define CCN_PR_UNSENT 0x01
interest has not been sent anywhere yet
#define CCN_PR_WAIT1 0x02
interest has been sent to one place
#define CCN_PR_STUFFED1 0x04
was stuffed before sent anywhere else
#define CCN_PR_TAP 0x08
at least one tap face is present
#define CCN_PR_EQV 0x10
a younger similar interest exists
#define CCN_PR_SCOPE0 0x20
interest scope is 0
#define CCN_PR_SCOPE1 0x40
interest scope is 1 (this host)
#define CCN_PR_SCOPE2 0x80
interest scope is 2 (immediate neighborhood)
#define CCN_FORW_REFRESHED (1 << 16)
private to ccnd
#define CCN_FWU_SECS 5
Determines how frequently we age our forwarding entries.
Typedefs
typedef unsigned ccn_accession_t
typedef int(* ccnd_logger )(void *loggerdata, const char *format, va_list ap)
Enumerations
enum cq_delay_class { CCN_CQ_ASAP, CCN_CQ_NORMAL, CCN_CQ_SLOW, CCN_CQ_N }
Functions
int ccnd_init_internal_keystore (struct ccnd_handle *)
int ccnd_internal_client_start (struct ccnd_handle *)
void ccnd_internal_client_stop (struct ccnd_handle *)
struct ccn_charbuf * ccnd_req_newface (struct ccnd_handle *h, const unsigned char *msg, size_t size)
The internal client calls this with the argument portion ARG of a face-creation request (/ccnx/CCNDID/newface/ARG) The result, if not NULL, will be used as the Content of the reply.
struct ccn_charbuf * ccnd_req_destroyface (struct ccnd_handle *h, const unsigned char *msg, size_t size)
The internal client calls this with the argument portion ARG of a face-destroy request (/ccnx/CCNDID/destroyface/ARG) The result, if not NULL, will be used as the Content of the reply.
struct ccn_charbuf * ccnd_req_prefixreg (struct ccnd_handle *h, const unsigned char *msg, size_t size)
The internal client calls this with the argument portion ARG of a prefix-registration request (/ccnx/CCNDID/prefixreg/ARG) The result, if not NULL, will be used as the Content of the reply.
struct ccn_charbuf * ccnd_req_selfreg (struct ccnd_handle *h, const unsigned char *msg, size_t size)
The internal client calls this with the argument portion ARG of a prefix-registration request for self (/ccnx/CCNDID/selfreg/ARG) The result, if not NULL, will be used as the Content of the reply.
struct ccn_charbuf * ccnd_req_unreg (struct ccnd_handle *h, const unsigned char *msg, size_t size)
The internal client calls this with the argument portion ARG of a prefix-unregistration request (/ccnx/CCNDID/unreg/ARG) The result, if not NULL, will be used as the Content of the reply.
int ccnd_reg_uri (struct ccnd_handle *h, const char *uri, unsigned faceid, int flags, int expires)
Register a prefix, expressed in the form of a URI.
struct face * ccnd_face_from_faceid (struct ccnd_handle *, unsigned)
Looks up a face based on its faceid.
void ccnd_face_status_change (struct ccnd_handle *, unsigned)
Called by ccnd when a face undergoes a substantive status change that should be reported to interested parties.
int ccnd_destroy_face (struct ccnd_handle *h, unsigned faceid)
Destroys the face identified by faceid.
void ccnd_send (struct ccnd_handle *h, struct face *face, const void *data, size_t size)
Send data to the face.
int ccnd_stats_handle_http_connection (struct ccnd_handle *, struct face *)
void ccnd_msg (struct ccnd_handle *, const char *,...)
Copyright (C) 2009,2010 Palo Alto Research Center, Inc.
void ccnd_debug_ccnb (struct ccnd_handle *h, int lineno, const char *msg, struct face *face, const unsigned char *ccnb, size_t ccnb_size)
Produce a ccnd debug trace entry.
struct ccnd_handle * ccnd_create (const char *, ccnd_logger, void *)
Start a new ccnd instance.
void ccnd_run (struct ccnd_handle *h)
Run the main loop of the ccnd.
void ccnd_destroy (struct ccnd_handle **)
Destroy the ccnd instance, releasing all associated resources.
Variables
const char * ccnd_usage_message
CCND Usage message.
Detailed Description
Private definitions for ccnd - the CCNx daemon.
Data structures are described here so that logging and status routines can be compiled separately.
Part of ccnd - the CCNx Daemon.
Copyright (C) 2008-2010 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file ccnd_private.h.
Define Documentation
#define CCN_CONTENT_ENTRY_PRECIOUS 4
Definition at line 237 of file ccnd_private.h.
Referenced by clean_deamon(), and process_incoming_content().
#define CCN_CONTENT_ENTRY_SLOWSEND 1
content_entry flags
Definition at line 235 of file ccnd_private.h.
Referenced by choose_content_delay_class(), and process_incoming_content().
#define CCN_CONTENT_ENTRY_STALE 2
Definition at line 236 of file ccnd_private.h.
Referenced by clean_deamon(), mark_stale(), process_incoming_content(), process_incoming_interest(), and remove_content().
#define CCN_FACE_CLOSING (1 << 13)
close stream when output is done
Definition at line 205 of file ccnd_private.h.
Referenced by ccnd_stats_handle_http_connection(), do_deferred_write(), and prepare_poll_fds().
#define CCN_FACE_CONNECTING (1 << 11)
Connect in progress.
Definition at line 203 of file ccnd_private.h.
Referenced by do_deferred_write(), make_connection(), and process_input().
#define CCN_FACE_DC (1 << 7)
Direct control face.
Definition at line 199 of file ccnd_private.h.
Referenced by ccnd_reg_prefix(), and do_propagate().
#define CCN_FACE_DGRAM (1 << 1)
Datagram interface, respect packets.
Definition at line 193 of file ccnd_private.h.
Referenced by ccnd_destroy_face(), ccnd_getboundsocket(), ccnd_listen_on_address(), ccnd_listen_on_wildcards(), ccnd_send(), check_dgram_faces(), choose_content_delay_class(), choose_face_delay(), get_dgram_source(), make_connection(), process_input(), and setup_multicast().
#define CCN_FACE_GG (1 << 2)
Considered friendly.
Definition at line 194 of file ccnd_private.h.
Referenced by adjust_outbound_for_existing_interests(), ccnd_create(), ccnd_reg_prefix(), ccnd_req_destroyface(), ccnd_req_newface(), ccnd_req_prefix_or_self_reg(), ccnd_req_unreg(), choose_content_delay_class(), choose_face_delay(), collect_faces_html(), get_dgram_source(), get_outbound_faces(), init_face_flags(), match_interests(), process_incoming_content(), process_incoming_interest(), process_input_message(), register_new_face(), and replan_propagation().
#define CCN_FACE_INET (1 << 4)
IPv4.
Definition at line 196 of file ccnd_private.h.
Referenced by init_face_flags(), and post_face_notice().
#define CCN_FACE_INET6 (1 << 6)
IPv6.
Definition at line 198 of file ccnd_private.h.
Referenced by init_face_flags(), and post_face_notice().
#define CCN_FACE_LINK (1 << 0)
face flags Elements wrapped by CCNProtocolDataUnit
Definition at line 192 of file ccnd_private.h.
Referenced by adjust_outbound_for_existing_interests(), choose_content_delay_class(), choose_face_delay(), make_connection(), process_input_message(), send_content(), setup_multicast(), and stuff_and_send().
#define CCN_FACE_LOCAL (1 << 3)
PF_UNIX socket.
Definition at line 195 of file ccnd_private.h.
Referenced by ccnd_create(), choose_content_delay_class(), choose_face_delay(), create_local_listener(), init_face_flags(), make_connection(), process_input(), and setup_multicast().
#define CCN_FACE_LOOPBACK (1 << 12)
v4 or v6 loopback address
Definition at line 204 of file ccnd_private.h.
Referenced by get_dgram_source(), init_face_flags(), and process_input_message().
#define CCN_FACE_MCAST (1 << 5)
a party line (e.g. multicast)
Definition at line 197 of file ccnd_private.h.
Referenced by adjust_outbound_for_existing_interests(), ccnd_destroy_face(), ccnd_shutdown_listeners(), choose_content_delay_class(), choose_face_delay(), collect_faces_html(), get_dgram_source(), prepare_poll_fds(), and setup_multicast().
#define CCN_FACE_NORECV (1 << 15)
use for sending only
Definition at line 207 of file ccnd_private.h.
Referenced by ccnd_getboundsocket(), and prepare_poll_fds().
#define CCN_FACE_NOSEND (1 << 8)
Don't send anymore.
Definition at line 200 of file ccnd_private.h.
Referenced by ccnd_send(), ccnd_stats_handle_http_connection(), collect_faces_html(), content_sender(), do_deferred_write(), do_propagate(), face_send_queue_insert(), handle_send_error(), make_connection(), send_content(), and setup_multicast().
#define CCN_FACE_PASSIVE (1 << 14)
a listener or a bound dgram socket
Definition at line 206 of file ccnd_private.h.
Referenced by ccnd_getboundsocket(), ccnd_listen_on_address(), ccnd_listen_on_wildcards(), ccnd_shutdown_listeners(), collect_faces_html(), create_local_listener(), process_input(), and register_new_face().
#define CCN_FACE_PERMANENT (1 << 10)
No timeout for inactivity.
Definition at line 202 of file ccnd_private.h.
Referenced by ccnd_req_newface(), and check_dgram_faces().
#define CCN_FACE_REGOK (1 << 16)
Allowed to do prefix registration.
Definition at line 208 of file ccnd_private.h.
Referenced by ccnd_reg_prefix(), and ccnd_req_prefix_or_self_reg().
#define CCN_FACE_UNDECIDED (1 << 9)
Might not be talking ccn.
Definition at line 201 of file ccnd_private.h.
Referenced by accept_connection(), collect_faces_html(), collect_faces_xml(), finalize_face(), make_connection(), process_input(), process_input_message(), and register_new_face().
#define CCN_FORW_REFRESHED (1 << 16)
private to ccnd
Definition at line 317 of file ccnd_private.h.
Referenced by age_forwarding(), and ccnd_reg_prefix().
#define CCN_FWU_SECS 5
Determines how frequently we age our forwarding entries.
Definition at line 322 of file ccnd_private.h.
Referenced by age_forwarding(), and age_forwarding_needed().
#define CCN_NOFACEID (~0U)
Definition at line 209 of file ccnd_private.h.
Referenced by ccnd_create(), ccnd_req_prefix_or_self_reg(), ccnd_req_unreg(), check_nameprefix_entries(), collect_faces_html(), collect_faces_xml(), faceid_from_fd(), finalize_face(), nameprefix_for_pe(), nameprefix_seek(), note_content_from(), record_connection(), reorder_outbound_using_history(), sending_fd(), shutdown_client_fd(), and update_forward_to().
#define CCN_PR_EQV 0x10
a younger similar interest exists
Definition at line 275 of file ccnd_private.h.
Referenced by adjust_outbound_for_existing_interests(), and replan_propagation().
#define CCN_PR_SCOPE0 0x20
interest scope is 0
Definition at line 276 of file ccnd_private.h.
Referenced by propagate_interest(), and replan_propagation().
#define CCN_PR_SCOPE1 0x40
interest scope is 1 (this host)
Definition at line 277 of file ccnd_private.h.
Referenced by propagate_interest(), and replan_propagation().
#define CCN_PR_SCOPE2 0x80
interest scope is 2 (immediate neighborhood)
Definition at line 278 of file ccnd_private.h.
Referenced by propagate_interest(), and replan_propagation().
#define CCN_PR_STUFFED1 0x04
was stuffed before sent anywhere else
Definition at line 273 of file ccnd_private.h.
Referenced by ccn_stuff_interest(), and do_propagate().
#define CCN_PR_TAP 0x08
at least one tap face is present
Definition at line 274 of file ccnd_private.h.
Referenced by do_propagate(), and propagate_interest().
#define CCN_PR_UNSENT 0x01
interest has not been sent anywhere yet
Definition at line 271 of file ccnd_private.h.
Referenced by ccn_stuff_interest(), do_propagate(), and propagate_interest().
#define CCN_PR_WAIT1 0x02
interest has been sent to one place
Definition at line 272 of file ccnd_private.h.
Referenced by ccn_stuff_interest(), and do_propagate().
#define FACESLOTBITS 18
Each face is referenced by a number, the faceid. The low-order bits (under the MAXFACES) constitute a slot number that is unique (for this ccnd) among the faces that are alive at a given time. The rest of the bits form a generation number that make the entire faceid unique over time, even for faces that are defunct.
Definition at line 151 of file ccnd_private.h.
#define MAXFACES ((1U << FACESLOTBITS) - 1)
Definition at line 152 of file ccnd_private.h.
Referenced by enroll_face(), face_from_faceid(), and finalize_face().
Typedef Documentation
typedef unsigned ccn_accession_t
Definition at line 57 of file ccnd_private.h.
typedef int(* ccnd_logger)(void *loggerdata, const char *format, va_list ap)
Definition at line 62 of file ccnd_private.h.
Enumeration Type Documentation
enum cq_delay_class
Enumerator:
CCN_CQ_ASAP
CCN_CQ_NORMAL
CCN_CQ_SLOW
CCN_CQ_N
Definition at line 164 of file ccnd_private.h.
Function Documentation
struct ccnd_handle* ccnd_create (const char * progname, ccnd_logger logger, void * loggerdata) [read]
Start a new ccnd instance. Parameters:
progname - name of program binary, used for locating helpers
logger - logger function
loggerdata - data to pass to logger function
Definition at line 4429 of file ccnd.c.
Referenced by main(), and start_ccnd().
void ccnd_debug_ccnb (struct ccnd_handle * h, int lineno, const char * msg, struct face * face, const unsigned char * ccnb, size_t ccnb_size)
Produce a ccnd debug trace entry. Output is produced by calling ccnd_msg.
Parameters:
h the ccnd handle
lineno caller's source line number (usually __LINE__)
msg a short text tag to identify the entry
face handle of associated face; may be NULL
ccnb points to ccnb-encoded Interest or ContentObject
ccnb_size is in bytes
Definition at line 79 of file android_msg.c.
Referenced by adjust_outbound_for_existing_interests(), age_forwarding(), ccn_stuff_interest(), ccnd_answer_req(), ccnd_reg_prefix(), ccnd_req_unreg(), consume_matching_interests(), do_propagate(), face_send_queue_insert(), find_first_match_candidate(), mark_stale(), next_child_at_level(), pe_next_usec(), process_incoming_content(), process_incoming_interest(), propagate_interest(), remove_content(), send_content(), and set_content_timer().
void ccnd_destroy (struct ccnd_handle **)
Destroy the ccnd instance, releasing all associated resources.
Definition at line 4579 of file ccnd.c.
Referenced by main().
int ccnd_destroy_face (struct ccnd_handle * h, unsigned faceid)
Destroys the face identified by faceid. Returns:
0 for success, -1 for failure.
Definition at line 1609 of file ccnd.c.
Referenced by ccnd_req_destroyface(), and ccnd_stats_handle_http_connection().
struct face* ccnd_face_from_faceid (struct ccnd_handle *, unsigned) [read]
Looks up a face based on its faceid.
Definition at line 205 of file ccnd.c.
Referenced by ccnd_collect_stats(), and post_face_notice().
void ccnd_face_status_change (struct ccnd_handle * ccnd, unsigned faceid)
Called by ccnd when a face undergoes a substantive status change that should be reported to interested parties. In the destroy case, this is called frome the hash table finalizer, so it shouldn't do much directly. Inspecting the face is OK, though.
Definition at line 522 of file ccnd_internal_client.c.
Referenced by ccnd_start_notice(), finalize_face(), and register_new_face().
int ccnd_init_internal_keystore (struct ccnd_handle *)
Definition at line 381 of file ccnd_internal_client.c.
Referenced by ccnd_create(), and ccnd_internal_client_start().
int ccnd_internal_client_start (struct ccnd_handle *)
Definition at line 570 of file ccnd_internal_client.c.
Referenced by ccnd_create().
void ccnd_internal_client_stop (struct ccnd_handle *)
Definition at line 627 of file ccnd_internal_client.c.
Referenced by ccnd_destroy().
void ccnd_msg (struct ccnd_handle * h, const char * fmt, ...)
Copyright (C) 2009,2010 Palo Alto Research Center, Inc. This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA. Logging support for ccnd, for Android platform Produce ccnd debug output to the Android log. Output is produced on stderr under the control of h->debug; prepends decimal timestamp and process identification. Caller should not supply newlines.
Parameters:
h the ccnd handle
fmt printf-like format string
Copyright (C) 2009,2010 Palo Alto Research Center, Inc.
Output is produced via h->logger under the control of h->debug; prepends decimal timestamp and process identification. Caller should not supply newlines.
Parameters:
h the ccnd handle
fmt printf-like format string
Definition at line 47 of file android_msg.c.
Referenced by accept_connection(), ccnd_close_fd(), ccnd_collect_stats(), ccnd_create(), ccnd_debug_ccnb(), ccnd_getboundsocket(), ccnd_init_internal_keystore(), ccnd_listen_on_address(), ccnd_listen_on_wildcards(), ccnd_new_face_msg(), ccnd_parse_uri_list(), ccnd_req_destroyface(), ccnd_req_newface(), ccnd_run(), ccnd_send(), ccnd_setsockopt_v6only(), ccnd_start_notice(), ccnd_stats_http_set_debug(), check_comm_file(), content_sender(), create_local_listener(), do_deferred_write(), establish_min_recv_bufsize(), face_send_queue_insert(), finalize_content(), finalize_face(), get_outbound_faces(), handle_send_error(), main(), make_connection(), nameprefix_longest_match(), note_content_from(), process_incoming_content(), process_incoming_interest(), process_input(), process_input_buffer(), process_input_message(), propagate_interest(), record_connection(), replan_propagation(), setup_multicast(), shutdown_client_fd(), start_ccnd(), and update_forward_to().
int ccnd_reg_uri (struct ccnd_handle * h, const char * uri, unsigned faceid, int flags, int expires)
Register a prefix, expressed in the form of a URI. Returns:
negative value for error, or new face flags for success.
Definition at line 2080 of file ccnd.c.
Referenced by ccnd_internal_client_start(), ccnd_reg_ccnx_ccndid(), ccnd_reg_uri_list(), and ccnd_uri_listen().
struct ccn_charbuf* ccnd_req_destroyface (struct ccnd_handle * h, const unsigned char * msg, size_t size) [read]
The internal client calls this with the argument portion ARG of a face-destroy request (/ccnx/CCNDID/destroyface/ARG) The result, if not NULL, will be used as the Content of the reply. The internal client calls this with the argument portion ARG of a face-destroy request (/ccnx/CCNDID/destroyface/ARG) The result, if not NULL, will be used as the Content of the reply.
Parameters:
h is the ccnd handle
msg points to a ccnd-encoded ContentObject containing a FaceInstance in its Content.
size is its size in bytes
Returns:
on success the returned charbuf holds a new ccnd-encoded FaceInstance including faceid; returns NULL for any error.
Is is an error if the face does not exist.
Definition at line 2285 of file ccnd.c.
Referenced by ccnd_answer_req().
struct ccn_charbuf* ccnd_req_newface (struct ccnd_handle * h, const unsigned char * msg, size_t size) [read]
The internal client calls this with the argument portion ARG of a face-creation request (/ccnx/CCNDID/newface/ARG) The result, if not NULL, will be used as the Content of the reply. The internal client calls this with the argument portion ARG of a face-creation request (/ccnx/CCNDID/newface/ARG) The result, if not NULL, will be used as the Content of the reply.
Parameters:
h is the ccnd handle
msg points to a ccnd-encoded ContentObject containing a FaceInstance in its Content.
size is its size in bytes
Returns:
on success the returned charbuf holds a new ccnd-encoded FaceInstance including faceid; returns NULL for any error.
Is is permitted for the face to already exist. A newly created face will have no registered prefixes, and so will not receive any traffic.
Definition at line 2159 of file ccnd.c.
Referenced by ccnd_answer_req().
struct ccn_charbuf* ccnd_req_prefixreg (struct ccnd_handle * h, const unsigned char * msg, size_t size) [read]
The internal client calls this with the argument portion ARG of a prefix-registration request (/ccnx/CCNDID/prefixreg/ARG) The result, if not NULL, will be used as the Content of the reply. The internal client calls this with the argument portion ARG of a prefix-registration request (/ccnx/CCNDID/prefixreg/ARG) The result, if not NULL, will be used as the Content of the reply.
Parameters:
h is the ccnd handle
msg points to a ccnd-encoded ContentObject containing a ForwardingEntry in its Content.
size is its size in bytes
Returns:
on success the returned charbuf holds a new ccnd-encoded ForwardingEntry; returns NULL for any error.
Definition at line 2431 of file ccnd.c.
Referenced by ccnd_answer_req().
struct ccn_charbuf* ccnd_req_selfreg (struct ccnd_handle * h, const unsigned char * msg, size_t size) [read]
The internal client calls this with the argument portion ARG of a prefix-registration request for self (/ccnx/CCNDID/selfreg/ARG) The result, if not NULL, will be used as the Content of the reply. The internal client calls this with the argument portion ARG of a prefix-registration request for self (/ccnx/CCNDID/selfreg/ARG) The result, if not NULL, will be used as the Content of the reply.
Parameters:
h is the ccnd handle
msg points to a ccnd-encoded ContentObject containing a ForwardingEntry in its Content.
size is its size in bytes
Returns:
on success the returned charbuf holds a new ccnd-encoded ForwardingEntry; returns NULL for any error.
Definition at line 2447 of file ccnd.c.
Referenced by ccnd_answer_req().
struct ccn_charbuf* ccnd_req_unreg (struct ccnd_handle * h, const unsigned char * msg, size_t size) [read]
The internal client calls this with the argument portion ARG of a prefix-unregistration request (/ccnx/CCNDID/unreg/ARG) The result, if not NULL, will be used as the Content of the reply. The internal client calls this with the argument portion ARG of a prefix-unregistration request (/ccnx/CCNDID/unreg/ARG) The result, if not NULL, will be used as the Content of the reply.
Parameters:
h is the ccnd handle
msg points to a ccnd-encoded ContentObject containing a ForwardingEntry in its Content.
size is its size in bytes
Returns:
on success the returned charbuf holds a new ccnd-encoded ForwardingEntry; returns NULL for any error.
Definition at line 2463 of file ccnd.c.
Referenced by ccnd_answer_req().
void ccnd_run (struct ccnd_handle * h)
Run the main loop of the ccnd.
Definition at line 4082 of file ccnd.c.
Referenced by main(), and start_ccnd().
void ccnd_send (struct ccnd_handle * h, struct face * face, const void * data, size_t size)
Send data to the face. No direct error result is provided; the face state is updated as needed.
Definition at line 3956 of file ccnd.c.
Referenced by ccnd_stats_handle_http_connection(), send_content(), send_http_response(), and stuff_and_send().
int ccnd_stats_handle_http_connection (struct ccnd_handle *, struct face *)
Definition at line 86 of file ccnd_stats.c.
Referenced by process_input().
Variable Documentation
const char* ccnd_usage_message
CCND Usage message.
Definition at line 132 of file ccnd_msg.c.
Referenced by ccnd_usage(), and main().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.