.TH "cmd/ccnget.c" 3 "4 Nov 2010" "Version 0.3.0" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmd/ccnget.c \- 
.PP
Get one content item matching the name prefix and write it to stdout.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBusage\fP (const char *progname)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Get one content item matching the name prefix and write it to stdout. 

Written as test for ccn_get, but probably useful for debugging.
.PP
A CCNx command-line utility.
.PP
Copyright (C) 2009-2010 Palo Alto Research Center, Inc.
.PP
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA. 
.PP
Definition in file \fBccnget.c\fP.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"
.PP
Definition at line 45 of file ccnget.c.
.SS "static void usage (const char * progname)\fC [static]\fP"
.PP
Definition at line 31 of file ccnget.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
