cmd/ccnhexdumpdata.c
NAME
cmd/ccnhexdumpdata.c -
Parse a ccnb-encoded ContentObject in a file and dump the content as hex data to stdout.
SYNOPSIS
Functions
static char * segment_prefix (char *path)
static int process_test (unsigned char *data, size_t n, struct fstate *perfilestate)
static int process_fd (int fd, struct fstate *perfilestate)
static int process_file (char *path, struct fstate *perfilestate)
int main (int argc, char *argv[])
Detailed Description
Parse a ccnb-encoded ContentObject in a file and dump the content as hex data to stdout.
A CCNx command-line utility.
Copyright (C) 2008, 2009 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file ccnhexdumpdata.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 164 of file ccnhexdumpdata.c.
static int process_fd (int fd, struct fstate * perfilestate) [static]
Definition at line 123 of file ccnhexdumpdata.c.
Referenced by process_file().
static int process_file (char * path, struct fstate * perfilestate) [static]
Definition at line 142 of file ccnhexdumpdata.c.
Referenced by main().
static int process_test (unsigned char * data, size_t n, struct fstate * perfilestate) [static]
Definition at line 54 of file ccnhexdumpdata.c.
Referenced by process_fd().
static char* segment_prefix (char * path) [static]
Definition at line 40 of file ccnhexdumpdata.c.
Referenced by process_file().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.