cmd/ccnslurp.c
NAME
cmd/ccnslurp.c -
Attempts pull everything in a branch of the ccn name hierarchy.
SYNOPSIS
Defines
#define EXCLUDE_LOW 1
#define EXCLUDE_HIGH 2
Functions
static int namecompare (const void *a, const void *b)
static struct upcalldata * get_my_data (struct ccn_closure *selfp)
static void append_bf_all (struct ccn_charbuf *c)
static int express_my_interest (struct ccn *h, struct ccn_closure *selfp, struct ccn_charbuf *name)
static struct ccn_closure * split_my_excludes (struct ccn_closure *selfp)
static enum ccn_upcall_res incoming_content (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *)
static struct ccn_charbuf * ccn_charbuf_duplicate (struct ccn_charbuf *)
static void answer_passive (struct ccn_charbuf *templ)
static struct ccn_charbuf * create_passive_templ (void)
void usage (const char *prog)
int main (int argc, char **argv)
Variables
static struct ccn_charbuf * passive_templ
Detailed Description
Attempts pull everything in a branch of the ccn name hierarchy.
A CCNx command-line utility.
Copyright (C) 2008, 2009 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file ccnslurp.c.
Define Documentation
#define EXCLUDE_HIGH 2
Definition at line 38 of file ccnslurp.c.
#define EXCLUDE_LOW 1
Definition at line 37 of file ccnslurp.c.
Function Documentation
static void answer_passive (struct ccn_charbuf * templ) [static]
Definition at line 240 of file ccnslurp.c.
Referenced by create_passive_templ(), and express_my_interest().
static void append_bf_all (struct ccn_charbuf * c) [static]
Definition at line 338 of file ccnslurp.c.
Referenced by express_my_interest().
static struct ccn_charbuf * ccn_charbuf_duplicate (struct ccn_charbuf * c) [static, read]
Definition at line 350 of file ccnslurp.c.
Referenced by split_my_excludes().
static struct ccn_charbuf* create_passive_templ (void) [static, read]
Definition at line 57 of file ccnslurp.c.
Referenced by main().
static int express_my_interest (struct ccn * h, struct ccn_closure * selfp, struct ccn_charbuf * name) [static]
Definition at line 253 of file ccnslurp.c.
Referenced by incoming_content().
static struct upcalldata * get_my_data (struct ccn_closure * selfp) [static, read]
Definition at line 85 of file ccnslurp.c.
Referenced by express_my_interest(), incoming_content(), and split_my_excludes().
static enum ccn_upcall_res incoming_content (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info) [static]
Definition at line 125 of file ccnslurp.c.
int main (int argc, char ** argv)
Definition at line 368 of file ccnslurp.c.
static int namecompare (const void * a, const void * b) [static]
Definition at line 75 of file ccnslurp.c.
Referenced by incoming_content().
static struct ccn_closure * split_my_excludes (struct ccn_closure * selfp) [static, read]
Definition at line 298 of file ccnslurp.c.
Referenced by incoming_content().
void usage (const char * prog)
Definition at line 358 of file ccnslurp.c.
Variable Documentation
struct ccn_charbuf* passive_templ [static]
Definition at line 55 of file ccnslurp.c.
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.