include/ccn/charbuf.h
NAME
include/ccn/charbuf.h -
Expandable character buffer for counted sequences of arbitrary octets.
SYNOPSIS
Data Structures
struct ccn_charbuf
Defines
#define CCN_DATETIME_PRECISION_USEC 6
#define CCN_DATETIME_PRECISION_MAX 6
Functions
struct ccn_charbuf * ccn_charbuf_create (void)
void ccn_charbuf_destroy (struct ccn_charbuf **cbp)
unsigned char * ccn_charbuf_reserve (struct ccn_charbuf *c, size_t n)
void ccn_charbuf_reset (struct ccn_charbuf *c)
int ccn_charbuf_append (struct ccn_charbuf *c, const void *p, size_t n)
int ccn_charbuf_append_value (struct ccn_charbuf *c, unsigned val, unsigned n)
int ccn_charbuf_append_charbuf (struct ccn_charbuf *c, const struct ccn_charbuf *i)
int ccn_charbuf_append_string (struct ccn_charbuf *c, const char *s)
int ccn_charbuf_putf (struct ccn_charbuf *c, const char *fmt,...)
int ccn_charbuf_append_datetime (struct ccn_charbuf *c, time_t secs, int nsecs)
int ccn_charbuf_append_datetime_now (struct ccn_charbuf *c, int precision)
char * ccn_charbuf_as_string (struct ccn_charbuf *c)
Detailed Description
Expandable character buffer for counted sequences of arbitrary octets.
Part of the CCNx C Library.
Copyright (C) 2008, 2009 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file charbuf.h.
Define Documentation
#define CCN_DATETIME_PRECISION_MAX 6
Definition at line 105 of file charbuf.h.
#define CCN_DATETIME_PRECISION_USEC 6
Definition at line 104 of file charbuf.h.
Function Documentation
int ccn_charbuf_append (struct ccn_charbuf * c, const void * p, size_t n)
Definition at line 80 of file ccn_charbuf.c.
Referenced by answer_passive(), append_bf_all(), append_future_vcomp(), ccn_append_link_name(), ccn_append_uri_component(), ccn_charbuf_append_charbuf(), ccn_charbuf_append_closer(), ccn_charbuf_append_datetime(), ccn_charbuf_append_string(), ccn_charbuf_append_tt(), ccn_charbuf_duplicate(), ccn_chk_signing_params(), ccn_construct_interest(), ccn_decoder_decode(), ccn_encode_Signature(), ccn_face_instance_parse(), ccn_forwarding_entry_parse(), ccn_get_public_key(), ccn_header_parse(), ccn_initiate_key_fetch(), ccn_load_private_key(), ccn_name_append(), ccn_name_append_components(), ccn_name_next_sibling(), ccn_parse_tagged_string(), ccn_put(), ccn_resolve_version(), ccn_seqw_create(), ccn_seqw_write(), ccn_sign_content(), ccn_signed_info_create(), ccn_stuff_interest(), ccn_uri_append(), ccn_uri_append_percentescaped(), ccnb_append_forwarding_entry(), ccnb_append_tagged_blob(), ccnd_answer_req(), ccnd_send(), do_character_data(), express_bulkdata_interest(), express_my_interest(), find_first_match_candidate(), handle_ping_response(), handle_simple_incoming_content(), incoming_content(), local_scope(), main(), make_template(), prefix_face_list_item_create(), process_incoming_content(), propagate_interest(), resolve_templ(), send_content(), sequenced_name(), seqw_next_cob(), and stuff_and_send().
int ccn_charbuf_append_charbuf (struct ccn_charbuf * c, const struct ccn_charbuf * i)
Definition at line 107 of file ccn_charbuf.c.
Referenced by ccn_encode_ContentObject(), ccn_get_header(), ccn_signed_info_create(), and ccnd_init_service_ccnb().
int ccn_charbuf_append_datetime (struct ccn_charbuf * c, time_t secs, int nsecs)
Definition at line 150 of file ccn_charbuf.c.
int ccn_charbuf_append_datetime_now (struct ccn_charbuf * c, int precision)
int ccn_charbuf_append_string (struct ccn_charbuf * c, const char * s)
Definition at line 113 of file ccn_charbuf.c.
Referenced by ccn_charbuf_append_sockaddr(), ccn_encode_Signature(), ccn_uri_append(), ccnb_append_number(), ccnd_init_service_ccnb(), and incoming_interest().
int ccn_charbuf_append_value (struct ccn_charbuf * c, unsigned val, unsigned n)
Definition at line 91 of file ccn_charbuf.c.
Referenced by ccn_decoder_decode(), ccn_extend_dict(), ccn_name_chop(), ccn_name_next_sibling(), ccn_parse_tagged_string(), ccn_signed_info_create(), ccnb_append_timestamp_blob(), ccnd_init_service_ccnb(), ccnd_listen_on(), and ccnd_parse_uri_list().
char* ccn_charbuf_as_string (struct ccn_charbuf * c)
Definition at line 176 of file ccn_charbuf.c.
Referenced by ccn_chk_signing_params(), ccn_extend_dict(), ccnd_debug_ccnb(), ccnd_init_internal_keystore(), ccnd_listen_on(), ccnd_reg_ccnx_ccndid(), ccnd_reg_prefix(), ccnd_reg_uri_list(), collect_faces_html(), collect_faces_xml(), incoming_content(), incoming_interest(), main(), pe_next_usec(), and process_prefix_face_list_item().
struct ccn_charbuf* ccn_charbuf_create (void) [read]
Definition at line 28 of file ccn_charbuf.c.
Referenced by age_forwarding(), ccn_charbuf_duplicate(), ccn_chk_signing_params(), ccn_create(), ccn_decoder_create(), ccn_decoder_decode(), ccn_encode_ContentObject(), ccn_encoder_create(), ccn_extend_dict(), ccn_face_instance_parse(), ccn_forwarding_entry_parse(), ccn_get_header(), ccn_header_parse(), ccn_initiate_key_fetch(), ccn_initiate_ping(), ccn_initiate_prefix_reg(), ccn_load_default_key(), ccn_load_private_key(), ccn_name_from_uri(), ccn_name_next_sibling(), ccn_process_input(), ccn_put(), ccn_resolve_version(), ccn_seqw_create(), ccn_sign_content(), ccnbx(), ccnd_answer_req(), ccnd_debug_ccnb(), ccnd_init_internal_keystore(), ccnd_init_service_ccnb(), ccnd_listen_on(), ccnd_msg(), ccnd_parse_uri_list(), ccnd_reg_ccnx_ccndid(), ccnd_reg_prefix(), ccnd_reg_uri(), ccnd_req_destroyface(), ccnd_req_newface(), ccnd_req_prefix_or_self_reg(), ccnd_req_unreg(), ccnd_send(), ccnd_start_notice(), ccnd_stats_http_set_debug(), ccnd_uri_listen(), charbuf_obtain(), collect_faces_html(), collect_faces_xml(), collect_forwarding_html(), collect_forwarding_xml(), collect_stats_html(), collect_stats_xml(), create_face(), create_passive_templ(), encode_message(), express_bulkdata_interest(), express_my_interest(), find_first_match_candidate(), get_ccndid(), handle_key(), handle_ping_response(), incoming_content(), incoming_interest(), init_all_chars_percent_encoded(), initialize_global_data(), local_scope_rm_template(), main(), make_connection(), make_template(), next_child_at_level(), pe_next_usec(), post_face_notice(), prefix_face_list_item_create(), process_command_tokens(), process_fd(), process_input(), process_prefix_face_list_item(), register_unregister_prefix(), resolve_templ(), sequenced_name(), seqw_next_cob(), and signed_info_create().
void ccn_charbuf_destroy (struct ccn_charbuf ** cbp)
Definition at line 36 of file ccn_charbuf.c.
Referenced by age_forwarding(), ask_more(), ccn_check_pub_arrival(), ccn_chk_signing_params(), ccn_decoder_decode(), ccn_decoder_destroy(), ccn_destroy(), ccn_destroy_interest(), ccn_disconnect(), ccn_encode_ContentObject(), ccn_encoder_destroy(), ccn_extend_dict(), ccn_face_instance_destroy(), ccn_face_instance_parse(), ccn_forwarding_entry_destroy(), ccn_forwarding_entry_parse(), ccn_get_header(), ccn_header_destroy(), ccn_initiate_key_fetch(), ccn_initiate_ping(), ccn_initiate_prefix_reg(), ccn_load_default_key(), ccn_load_private_key(), ccn_name_from_uri(), ccn_name_next_sibling(), ccn_resolve_version(), ccn_seqw_create(), ccn_seqw_write(), ccn_sign_content(), ccnbx(), ccnd_answer_req(), ccnd_debug_ccnb(), ccnd_destroy(), ccnd_init_internal_keystore(), ccnd_init_service_ccnb(), ccnd_internal_client_stop(), ccnd_listen_on(), ccnd_msg(), ccnd_parse_uri_list(), ccnd_reg_ccnx_ccndid(), ccnd_reg_prefix(), ccnd_reg_uri(), ccnd_req_destroyface(), ccnd_req_newface(), ccnd_req_prefix_or_self_reg(), ccnd_req_unreg(), ccnd_start_notice(), ccnd_stats_handle_http_connection(), ccnd_stats_http_set_debug(), ccnd_uri_listen(), charbuf_release(), collect_faces_html(), collect_faces_xml(), collect_forwarding_html(), collect_forwarding_xml(), create_face(), do_deferred_write(), encode_message(), express_bulkdata_interest(), express_my_interest(), fill_holes(), finalize_face(), find_first_match_candidate(), get_ccndid(), handle_key(), handle_send_error(), incoming_content(), init_all_chars_percent_encoded(), main(), next_child_at_level(), pe_next_usec(), post_face_notice(), prefix_face_list_destroy(), prefix_face_list_item_create(), process_fd(), process_internal_client_buffer(), process_prefix_face_list_item(), register_unregister_prefix(), resolve_templ(), sequenced_name(), seqw_incoming_interest(), seqw_next_cob(), shutdown_client_fd(), and signed_info_create().
int ccn_charbuf_putf (struct ccn_charbuf * c, const char * fmt, ...)
Definition at line 119 of file ccn_charbuf.c.
Referenced by ccn_chk_signing_params(), ccn_decimal_seqfunc(), ccn_uri_append_percentescaped(), ccnd_debug_ccnb(), ccnd_init_internal_keystore(), ccnd_msg(), ccnd_reg_prefix(), ccnd_stats_http_set_debug(), collect_faces_html(), collect_faces_xml(), collect_forwarding_html(), collect_forwarding_xml(), collect_stats_html(), collect_stats_xml(), incoming_content(), init_all_chars_percent_encoded(), main(), pe_next_usec(), post_face_notice(), and sequenced_name().
unsigned char* ccn_charbuf_reserve (struct ccn_charbuf * c, size_t n)
Definition at line 51 of file ccn_charbuf.c.
Referenced by append_bloom_element(), ccn_append_pubkey_blob(), ccn_binary_seqfunc(), ccn_charbuf_append(), ccn_charbuf_append_sockaddr(), ccn_charbuf_append_value(), ccn_charbuf_as_string(), ccn_charbuf_putf(), ccn_decoder_decode(), ccn_encoder_create(), ccn_name_append(), ccn_name_append_components(), ccn_name_from_uri(), ccn_process_input(), ccnb_append_timestamp_blob(), ccnb_tagged_putf(), ccnbx(), ccnd_append_plain_nonce(), finish_openudata(), main(), process_fd(), process_input(), and stuff_and_send().
void ccn_charbuf_reset (struct ccn_charbuf * c)
Definition at line 71 of file ccn_charbuf.c.
Referenced by ccn_extend_dict(), ccn_get_header(), and main().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.