lib/encodedecodetest.c
NAME
lib/encodedecodetest.c -
Unit tests for CCNx C library.
SYNOPSIS
Functions
struct path * path_create (char *strpath)
void path_destroy (struct path **path)
int encode_message (struct ccn_charbuf *message, struct path *name_path, char *data, size_t len, struct ccn_charbuf *signed_info, const void *pkey)
int decode_message (struct ccn_charbuf *message, struct path *name_path, char *data, size_t len, const void *verkey)
int expected_res (int res, char code)
static void init_all_chars_percent_encoded (void)
int main (int argc, char *argv[])
Variables
static char all_chars_percent_encoded [256 *3+1]
static const char * all_chars_percent_encoded_canon
Detailed Description
Unit tests for CCNx C library.
A CCNx program.
Copyright (C) 2009-2010 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file encodedecodetest.c.
Function Documentation
int decode_message (struct ccn_charbuf * message, struct path * name_path, char * data, size_t len, const void * verkey)
Definition at line 93 of file encodedecodetest.c.
Referenced by main().
int encode_message (struct ccn_charbuf * message, struct path * name_path, char * data, size_t len, struct ccn_charbuf * signed_info, const void * pkey)
Definition at line 68 of file encodedecodetest.c.
Referenced by main().
int expected_res (int res, char code)
Definition at line 144 of file encodedecodetest.c.
Referenced by main().
static void init_all_chars_percent_encoded (void) [static]
Definition at line 160 of file encodedecodetest.c.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 191 of file encodedecodetest.c.
struct path* path_create (char * strpath) [read]
Definition at line 41 of file encodedecodetest.c.
Referenced by main().
void path_destroy (struct path ** path)
Definition at line 62 of file encodedecodetest.c.
Referenced by main().
Variable Documentation
char all_chars_percent_encoded[256 *3+1] [static]
Definition at line 158 of file encodedecodetest.c.
Referenced by init_all_chars_percent_encoded(), and main().
const char* all_chars_percent_encoded_canon [static]"Initial value:
 'ccnx:/'
 '%00%01%02%03%04%05%06%07%08%09%0A%0B%0C%0D%0E%0F'
 '%10%11%12%13%14%15%16%17%18%19%1A%1B%1C%1D%1E%1F'
 '%20%21%22%23%24%25%26%27%28%29%2A%2B%2C-.%2F'
 '0123456789%3A%3B%3C%3D%3E%3F'
 '%40ABCDEFGHIJKLMNOPQRSTUVWXYZ%5B%5C%5D%5E_'
 '%60abcdefghijklmnopqrstuvwxyz%7B%7C%7D~%7F'
 '%80%81%82%83%84%85%86%87%88%89%8A%8B%8C%8D%8E%8F'
 '%90%91%92%93%94%95%96%97%98%99%9A%9B%9C%9D%9E%9F'
 '%A0%A1%A2%A3%A4%A5%A6%A7%A8%A9%AA%AB%AC%AD%AE%AF'
 '%B0%B1%B2%B3%B4%B5%B6%B7%B8%B9%BA%BB%BC%BD%BE%BF'
 '%C0%C1%C2%C3%C4%C5%C6%C7%C8%C9%CA%CB%CC%CD%CE%CF'
 '%D0%D1%D2%D3%D4%D5%D6%D7%D8%D9%DA%DB%DC%DD%DE%DF'
 '%E0%E1%E2%E3%E4%E5%E6%E7%E8%E9%EA%EB%EC%ED%EE%EF'
 '%F0%F1%F2%F3%F4%F5%F6%F7%F8%F9%FA%FB%FC%FD%FE%FF'
Definition at line 173 of file encodedecodetest.c.
Referenced by main().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.