include/ccn/header.h
NAME
include/ccn/header.h -
Part of the CCNx C Library.
SYNOPSIS
Data Structures
struct ccn_header
Functions
struct ccn_header * ccn_header_parse (const unsigned char *, size_t)
Parse a ccnb-encoded Header.
void ccn_header_destroy (struct ccn_header **)
int ccnb_append_header (struct ccn_charbuf *, const struct ccn_header *)
struct ccn_header * ccn_get_header (struct ccn *, struct ccn_charbuf *, int)
Detailed Description
Part of the CCNx C Library.
Copyright (C) 2009 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file header.h.
Function Documentation
struct ccn_header* ccn_get_header (struct ccn *, struct ccn_charbuf *, int) [read]
Definition at line 137 of file ccn_header.c.
void ccn_header_destroy (struct ccn_header **)
Definition at line 104 of file ccn_header.c.
Referenced by ccn_header_parse(), and main().
struct ccn_header* ccn_header_parse (const unsigned char *, size_t) [read]
Parse a ccnb-encoded Header.
Definition at line 50 of file ccn_header.c.
Referenced by ccn_get_header(), and main().
int ccnb_append_header (struct ccn_charbuf *, const struct ccn_header *)
Definition at line 115 of file ccn_header.c.
Referenced by main().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.