include/ccn/matrix.h
NAME
include/ccn/matrix.h -
Part of the CCNx C Library.
SYNOPSIS
Data Structures
struct ccn_matrix_bounds
Functions
struct ccn_matrix * ccn_matrix_create (void)
void ccn_matrix_destroy (struct ccn_matrix **)
intptr_t ccn_matrix_fetch (struct ccn_matrix *m, uint_least64_t row, unsigned col)
void ccn_matrix_store (struct ccn_matrix *m, uint_least64_t row, unsigned col, intptr_t value)
int ccn_matrix_getbounds (struct ccn_matrix *m, struct ccn_matrix_bounds *result)
int ccn_matrix_trim (struct ccn_matrix *m, const struct ccn_matrix_bounds *bounds)
int ccn_matrix_clear (struct ccn_matrix *m, const struct ccn_matrix_bounds *bounds)
Detailed Description
Part of the CCNx C Library.
Copyright (C) 2008, 2009 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Implements a two-dimension table containing integer values. Although this interface is abstract, the implementation is (or will be) tuned to the needs of ccnd. Any value not stored will fetch as zero.
Definition in file matrix.h.
Function Documentation
int ccn_matrix_clear (struct ccn_matrix * m, const struct ccn_matrix_bounds * bounds)
Definition at line 144 of file ccn_matrix.c.
struct ccn_matrix* ccn_matrix_create (void) [read]
Definition at line 39 of file ccn_matrix.c.
Referenced by main().
void ccn_matrix_destroy (struct ccn_matrix **)
Definition at line 52 of file ccn_matrix.c.
Referenced by main().
intptr_t ccn_matrix_fetch (struct ccn_matrix * m, uint_least64_t row, unsigned col)
Definition at line 66 of file ccn_matrix.c.
Referenced by main().
int ccn_matrix_getbounds (struct ccn_matrix * m, struct ccn_matrix_bounds * result)
Definition at line 98 of file ccn_matrix.c.
Referenced by Dump().
void ccn_matrix_store (struct ccn_matrix * m, uint_least64_t row, unsigned col, intptr_t value)
Definition at line 78 of file ccn_matrix.c.
Referenced by main().
int ccn_matrix_trim (struct ccn_matrix * m, const struct ccn_matrix_bounds * bounds)
Definition at line 134 of file ccn_matrix.c.
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.