.TH "MP_info_st" 3 "4 Nov 2010" "Version 0.3.0" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MP_info_st \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (ASN1_OCTET_STRING)*hashes"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ASN1_INTEGER * \fBnode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 55 of file merklepathasn1.h.
.SH "Member Function Documentation"
.PP 
.SS "MP_info_st::STACK_OF (ASN1_OCTET_STRING)"
.SH "Field Documentation"
.PP 
.SS "ASN1_INTEGER* \fBMP_info_st::node\fP"
.PP
Definition at line 56 of file merklepathasn1.h.
.PP
Referenced by ccn_merkle_root_hash(), and ccn_verify_signature().

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
