include/ccn/reg_mgmt.h
NAME
include/ccn/reg_mgmt.h -
Part of the CCNx C Library.
SYNOPSIS
Data Structures
struct ccn_forwarding_entry
Defines
#define CCN_FORW_ACTIVE 1
#define CCN_FORW_CHILD_INHERIT 2
#define CCN_FORW_ADVERTISE 4
#define CCN_FORW_LAST 8
#define CCN_FORW_CAPTURE 16
#define CCN_FORW_LOCAL 32
#define CCN_FORW_TAP 64
#define CCN_FORW_PUBMASK
Functions
struct ccn_forwarding_entry * ccn_forwarding_entry_parse (const unsigned char *p, size_t size)
void ccn_forwarding_entry_destroy (struct ccn_forwarding_entry **)
Destroy the result of ccn_forwarding_entry_parse().
int ccnb_append_forwarding_entry (struct ccn_charbuf *, const struct ccn_forwarding_entry *)
Detailed Description
Part of the CCNx C Library.
Copyright (C) 2009-2010 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file reg_mgmt.h.
Define Documentation
#define CCN_FORW_ACTIVE 1
Definition at line 37 of file reg_mgmt.h.
Referenced by ccn_set_interest_filter(), ccnd_internal_client_start(), ccnd_reg_ccnx_ccndid(), ccnd_uri_listen(), collect_forwarding_html(), collect_forwarding_xml(), main(), register_new_face(), seek_forwarding(), and update_forward_to().
#define CCN_FORW_ADVERTISE 4
Definition at line 39 of file reg_mgmt.h.
Referenced by ccnd_reg_ccnx_ccndid().
#define CCN_FORW_CAPTURE 16
Definition at line 41 of file reg_mgmt.h.
Referenced by ccnd_reg_ccnx_ccndid(), and update_forward_to().
#define CCN_FORW_CHILD_INHERIT 2
Definition at line 38 of file reg_mgmt.h.
Referenced by ccn_set_interest_filter(), ccnd_internal_client_start(), ccnd_reg_ccnx_ccndid(), ccnd_uri_listen(), main(), register_new_face(), seek_forwarding(), and update_forward_to().
#define CCN_FORW_LAST 8
Definition at line 40 of file reg_mgmt.h.
Referenced by ccnd_reg_prefix(), main(), and update_forward_to().
#define CCN_FORW_LOCAL 32
Definition at line 42 of file reg_mgmt.h.
Referenced by ccnd_internal_client_start(), get_outbound_faces(), match_interests(), process_incoming_interest(), and replan_propagation().
#define CCN_FORW_PUBMASK"Value:
(CCN_FORW_ACTIVE | \
                          CCN_FORW_CHILD_INHERIT | \
                          CCN_FORW_ADVERTISE | \
                          CCN_FORW_LAST | \
                          CCN_FORW_CAPTURE | \
                          CCN_FORW_LOCAL | \
                          CCN_FORW_TAP )
Definition at line 44 of file reg_mgmt.h.
Referenced by ccnd_reg_prefix(), and process_command_tokens().
#define CCN_FORW_TAP 64
Definition at line 43 of file reg_mgmt.h.
Referenced by update_forward_to().
Function Documentation
void ccn_forwarding_entry_destroy (struct ccn_forwarding_entry **)
Destroy the result of ccn_forwarding_entry_parse().
Definition at line 101 of file ccn_reg_mgmt.c.
Referenced by ccn_forwarding_entry_parse(), ccnd_req_prefix_or_self_reg(), ccnd_req_unreg(), handle_prefix_reg_reply(), main(), and register_unregister_prefix().
struct ccn_forwarding_entry* ccn_forwarding_entry_parse (const unsigned char * p, size_t size) [read]
Definition at line 30 of file ccn_reg_mgmt.c.
Referenced by ccnd_req_prefix_or_self_reg(), ccnd_req_unreg(), handle_prefix_reg_reply(), main(), and register_unregister_prefix().
int ccnb_append_forwarding_entry (struct ccn_charbuf *, const struct ccn_forwarding_entry *)
Definition at line 111 of file ccn_reg_mgmt.c.
Referenced by ccn_initiate_prefix_reg(), ccnd_req_prefix_or_self_reg(), ccnd_req_unreg(), main(), and register_unregister_prefix().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.