.TH "include/ccn/schedule.h" 3 "4 Nov 2010" "Version 0.3.0" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ccn/schedule.h \- 
.PP
Event scheduling.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBccn_timeval\fP"
.br
.ti -1c
.RI "struct \fBccn_gettime\fP"
.br
.ti -1c
.RI "struct \fBccn_scheduled_event\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBCCN_SCHEDULE_CANCEL\fP   0x10"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBccn_gettime_action\fP )(const struct \fBccn_gettime\fP *, struct \fBccn_timeval\fP *)"
.br
.ti -1c
.RI "typedef int(* \fBccn_scheduled_action\fP )(struct ccn_schedule *sched, void *clienth, struct \fBccn_scheduled_event\fP *ev, int flags)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct ccn_schedule * \fBccn_schedule_create\fP (void *clienth, const struct \fBccn_gettime\fP *ccnclock)"
.br
.ti -1c
.RI "void \fBccn_schedule_destroy\fP (struct ccn_schedule **schedp)"
.br
.ti -1c
.RI "struct \fBccn_gettime\fP * \fBccn_schedule_get_gettime\fP (struct ccn_schedule *)"
.br
.ti -1c
.RI "struct \fBccn_scheduled_event\fP * \fBccn_schedule_event\fP (struct ccn_schedule *sched, int micros, \fBccn_scheduled_action\fP action, void *evdata, intptr_t evint)"
.br
.ti -1c
.RI "int \fBccn_schedule_cancel\fP (struct ccn_schedule *, struct \fBccn_scheduled_event\fP *)"
.br
.RI "\fICancel a scheduled event. \fP"
.ti -1c
.RI "int \fBccn_schedule_run\fP (struct ccn_schedule *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Event scheduling. 

Part of the CCNx C Library.
.PP
Copyright (C) 2008, 2009 Palo Alto Research Center, Inc.
.PP
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 
.PP
Definition in file \fBschedule.h\fP.
.SH "Define Documentation"
.PP 
.SS "#define CCN_SCHEDULE_CANCEL   0x10"
.PP
Definition at line 59 of file schedule.h.
.PP
Referenced by age_forwarding(), ccn_schedule_cancel(), ccn_schedule_destroy(), ccnd_internal_client_refresh(), ccnd_notice_push(), clean_deamon(), content_sender(), do_propagate(), expire_content(), fill_holes(), reap(), and reporter().
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* \fBccn_gettime_action\fP)(const struct \fBccn_gettime\fP *, struct \fBccn_timeval\fP *)"
.PP
Definition at line 43 of file schedule.h.
.SS "typedef int(* \fBccn_scheduled_action\fP)(struct ccn_schedule *sched, void *clienth, struct \fBccn_scheduled_event\fP *ev, int flags)"
.PP
Definition at line 60 of file schedule.h.
.SH "Function Documentation"
.PP 
.SS "int ccn_schedule_cancel (struct ccn_schedule * sched, struct \fBccn_scheduled_event\fP * ev)"
.PP
Cancel a scheduled event. Cancels the event (calling action with CCN_SCHEDULE_CANCEL set) 
.PP
\fBReturns:\fP
.RS 4
0 if OK, or -1 if this is not possible. 
.RE
.PP

.PP
Definition at line 254 of file ccn_schedule.c.
.PP
Referenced by ccnd_internal_client_reschedule(), ccnd_internal_client_stop(), and content_queue_destroy().
.SS "struct ccn_schedule* ccn_schedule_create (void * clienth, const struct \fBccn_gettime\fP * ccnclock)\fC [read]\fP"
.PP
Definition at line 88 of file ccn_schedule.c.
.PP
Referenced by ccnd_create(), and main().
.SS "void ccn_schedule_destroy (struct ccn_schedule ** schedp)"
.PP
Definition at line 103 of file ccn_schedule.c.
.PP
Referenced by ccnd_destroy(), incoming_content(), and main().
.SS "struct \fBccn_scheduled_event\fP* ccn_schedule_event (struct ccn_schedule * sched, int micros, \fBccn_scheduled_action\fP action, void * evdata, intptr_t evint)\fC [read]\fP"
.PP
Definition at line 222 of file ccn_schedule.c.
.PP
Referenced by age_forwarding_needed(), ccnd_face_status_change(), ccnd_internal_client_reschedule(), ccnd_internal_client_start(), clean_needed(), face_send_queue_insert(), main(), propagate_interest(), reap_needed(), set_content_timer(), and update_rtt().
.SS "struct \fBccn_gettime\fP* ccn_schedule_get_gettime (struct ccn_schedule *)\fC [read]\fP"
.PP
Definition at line 129 of file ccn_schedule.c.
.SS "int ccn_schedule_run (struct ccn_schedule *)"
.PP
Definition at line 301 of file ccn_schedule.c.
.PP
Referenced by ccnd_run(), and main().
.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
