.TH "lib/signbenchtest.c" 3 "4 Nov 2010" "Version 0.3.0" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/signbenchtest.c \- 
.PP
A simple test program to benchmark signing performance.  

.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBFRESHNESS\fP   10"
.br
.ti -1c
.RI "#define \fBCOUNT\fP   3000"
.br
.ti -1c
.RI "#define \fBPAYLOAD_SIZE\fP   51"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple test program to benchmark signing performance. 

Copyright (C) 2009 Palo Alto Research Center, Inc.
.PP
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA. 
.PP
Definition in file \fBsignbenchtest.c\fP.
.SH "Define Documentation"
.PP 
.SS "#define COUNT   3000"
.PP
Definition at line 30 of file signbenchtest.c.
.PP
Referenced by main().
.SS "#define FRESHNESS   10"
.PP
Definition at line 29 of file signbenchtest.c.
.PP
Referenced by main().
.SS "#define PAYLOAD_SIZE   51"
.PP
Definition at line 31 of file signbenchtest.c.
.PP
Referenced by main().
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"
.PP
Definition at line 34 of file signbenchtest.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
