lib/skel_decode_test.c
NAME
lib/skel_decode_test.c -
A simple test program for exercising ccn_skeleton_decoder.
SYNOPSIS
Defines
#define SHOW_HEX_STATE 1
Functions
static int process_test (unsigned char *data, size_t n, int flags)
static int process_fd (int fd, int flags)
static int process_file (char *path, int flags)
int main (int argc, char **argv)
Variables
static const char * tt_name [8]
Detailed Description
A simple test program for exercising ccn_skeleton_decoder.
A CCNx program.
Copyright (C) 2009 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file skel_decode_test.c.
Define Documentation
#define SHOW_HEX_STATE 1
Definition at line 43 of file skel_decode_test.c.
Referenced by main(), and process_test().
Function Documentation
int main (int argc, char ** argv)
Definition at line 138 of file skel_decode_test.c.
static int process_fd (int fd, int flags) [static]
Definition at line 90 of file skel_decode_test.c.
Referenced by process_file().
static int process_file (char * path, int flags) [static]
Definition at line 120 of file skel_decode_test.c.
Referenced by main().
static int process_test (unsigned char * data, size_t n, int flags) [static]
Definition at line 46 of file skel_decode_test.c.
Referenced by process_fd().
Variable Documentation
const char* tt_name[8] [static]"Initial value:
 {
    [CCN_EXT] = 'CCN_EXT',
    [CCN_TAG] = 'CCN_TAG',
    [CCN_DTAG] = 'CCN_DTAG',
    [CCN_ATTR] = 'CCN_ATTR',
    [CCN_DATTR] = 'CCN_DATTR',
    [CCN_BLOB] = 'CCN_BLOB',
    [CCN_UDATA] = 'CCN_UDATA',
    [CCN_NO_TOKEN] = 'CCN_CLOSE'
}
Definition at line 32 of file skel_decode_test.c.
Referenced by process_test().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.