libexec/udplink.c
NAME
libexec/udplink.c -
A CCNx link adaptor for UDP.
SYNOPSIS
Defines
#define UDPMAXBUF 8800
Functions
void udplink_fatal (int line, char *format,...)
void usage (char *name)
void udplink_note (char *format,...)
void udplink_print_data (char *source, unsigned char *data, int start, int length, int logging)
ssize_t send_remote_unencapsulated (int s, struct addrinfo *r, unsigned char *buf, size_t start, size_t length)
void process_options (int argc, char *const argv[], struct options *opt)
void set_multicast_sockopt (int socket_r, int socket_w, struct addrinfo *ai, struct options *opt)
void changeloglevel (int s)
int main (int argc, char *const argv[])
Detailed Description
A CCNx link adaptor for UDP.
Note:
Normally ccnd handles UDP directly, so this module is not used.
A CCNx program.
Copyright (C) 2008, 2009 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file udplink.c.
Define Documentation
#define UDPMAXBUF 8800
Definition at line 51 of file udplink.c.
Referenced by main().
Function Documentation
void changeloglevel (int s)
Definition at line 321 of file udplink.c.
Referenced by main().
int main (int argc, char *const argv[])
Definition at line 336 of file udplink.c.
void process_options (int argc, char *const argv[], struct options * opt)
Definition at line 139 of file udplink.c.
Referenced by main().
ssize_t send_remote_unencapsulated (int s, struct addrinfo * r, unsigned char * buf, size_t start, size_t length)
Definition at line 128 of file udplink.c.
Referenced by main().
void set_multicast_sockopt (int socket_r, int socket_w, struct addrinfo * ai, struct options * opt)
Definition at line 248 of file udplink.c.
Referenced by main().
void udplink_fatal (int line, char * format, ...)
Definition at line 86 of file udplink.c.
Referenced by main(), process_options(), and set_multicast_sockopt().
void udplink_note (char * format, ...)
Definition at line 99 of file udplink.c.
Referenced by changeloglevel(), main(), process_options(), set_multicast_sockopt(), and udplink_print_data().
void udplink_print_data (char * source, unsigned char * data, int start, int length, int logging)
Definition at line 111 of file udplink.c.
Referenced by main().
void usage (char * name)
Definition at line 81 of file udplink.c.
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.